// Code generated by ent, DO NOT EDIT.

package worldsetting

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/ai-novel/studio/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.WorldSetting {
	return predicate.WorldSetting(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.WorldSetting {
	return predicate.WorldSetting(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.WorldSetting {
	return predicate.WorldSetting(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.WorldSetting {
	return predicate.WorldSetting(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.WorldSetting {
	return predicate.WorldSetting(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.WorldSetting {
	return predicate.WorldSetting(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.WorldSetting {
	return predicate.WorldSetting(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.WorldSetting {
	return predicate.WorldSetting(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.WorldSetting {
	return predicate.WorldSetting(sql.FieldLTE(FieldID, id))
}

// NovelID applies equality check predicate on the "novel_id" field. It's identical to NovelIDEQ.
func NovelID(v string) predicate.WorldSetting {
	return predicate.WorldSetting(sql.FieldEQ(FieldNovelID, v))
}

// Category applies equality check predicate on the "category" field. It's identical to CategoryEQ.
func Category(v string) predicate.WorldSetting {
	return predicate.WorldSetting(sql.FieldEQ(FieldCategory, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.WorldSetting {
	return predicate.WorldSetting(sql.FieldEQ(FieldName, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.WorldSetting {
	return predicate.WorldSetting(sql.FieldEQ(FieldDescription, v))
}

// CurrentState applies equality check predicate on the "current_state" field. It's identical to CurrentStateEQ.
func CurrentState(v string) predicate.WorldSetting {
	return predicate.WorldSetting(sql.FieldEQ(FieldCurrentState, v))
}

// StateVersioned applies equality check predicate on the "state_versioned" field. It's identical to StateVersionedEQ.
func StateVersioned(v bool) predicate.WorldSetting {
	return predicate.WorldSetting(sql.FieldEQ(FieldStateVersioned, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.WorldSetting {
	return predicate.WorldSetting(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.WorldSetting {
	return predicate.WorldSetting(sql.FieldEQ(FieldUpdatedAt, v))
}

// NovelIDEQ applies the EQ predicate on the "novel_id" field.
func NovelIDEQ(v string) predicate.WorldSetting {
	return predicate.WorldSetting(sql.FieldEQ(FieldNovelID, v))
}

// NovelIDNEQ applies the NEQ predicate on the "novel_id" field.
func NovelIDNEQ(v string) predicate.WorldSetting {
	return predicate.WorldSetting(sql.FieldNEQ(FieldNovelID, v))
}

// NovelIDIn applies the In predicate on the "novel_id" field.
func NovelIDIn(vs ...string) predicate.WorldSetting {
	return predicate.WorldSetting(sql.FieldIn(FieldNovelID, vs...))
}

// NovelIDNotIn applies the NotIn predicate on the "novel_id" field.
func NovelIDNotIn(vs ...string) predicate.WorldSetting {
	return predicate.WorldSetting(sql.FieldNotIn(FieldNovelID, vs...))
}

// NovelIDGT applies the GT predicate on the "novel_id" field.
func NovelIDGT(v string) predicate.WorldSetting {
	return predicate.WorldSetting(sql.FieldGT(FieldNovelID, v))
}

// NovelIDGTE applies the GTE predicate on the "novel_id" field.
func NovelIDGTE(v string) predicate.WorldSetting {
	return predicate.WorldSetting(sql.FieldGTE(FieldNovelID, v))
}

// NovelIDLT applies the LT predicate on the "novel_id" field.
func NovelIDLT(v string) predicate.WorldSetting {
	return predicate.WorldSetting(sql.FieldLT(FieldNovelID, v))
}

// NovelIDLTE applies the LTE predicate on the "novel_id" field.
func NovelIDLTE(v string) predicate.WorldSetting {
	return predicate.WorldSetting(sql.FieldLTE(FieldNovelID, v))
}

// NovelIDContains applies the Contains predicate on the "novel_id" field.
func NovelIDContains(v string) predicate.WorldSetting {
	return predicate.WorldSetting(sql.FieldContains(FieldNovelID, v))
}

// NovelIDHasPrefix applies the HasPrefix predicate on the "novel_id" field.
func NovelIDHasPrefix(v string) predicate.WorldSetting {
	return predicate.WorldSetting(sql.FieldHasPrefix(FieldNovelID, v))
}

// NovelIDHasSuffix applies the HasSuffix predicate on the "novel_id" field.
func NovelIDHasSuffix(v string) predicate.WorldSetting {
	return predicate.WorldSetting(sql.FieldHasSuffix(FieldNovelID, v))
}

// NovelIDEqualFold applies the EqualFold predicate on the "novel_id" field.
func NovelIDEqualFold(v string) predicate.WorldSetting {
	return predicate.WorldSetting(sql.FieldEqualFold(FieldNovelID, v))
}

// NovelIDContainsFold applies the ContainsFold predicate on the "novel_id" field.
func NovelIDContainsFold(v string) predicate.WorldSetting {
	return predicate.WorldSetting(sql.FieldContainsFold(FieldNovelID, v))
}

// CategoryEQ applies the EQ predicate on the "category" field.
func CategoryEQ(v string) predicate.WorldSetting {
	return predicate.WorldSetting(sql.FieldEQ(FieldCategory, v))
}

// CategoryNEQ applies the NEQ predicate on the "category" field.
func CategoryNEQ(v string) predicate.WorldSetting {
	return predicate.WorldSetting(sql.FieldNEQ(FieldCategory, v))
}

// CategoryIn applies the In predicate on the "category" field.
func CategoryIn(vs ...string) predicate.WorldSetting {
	return predicate.WorldSetting(sql.FieldIn(FieldCategory, vs...))
}

// CategoryNotIn applies the NotIn predicate on the "category" field.
func CategoryNotIn(vs ...string) predicate.WorldSetting {
	return predicate.WorldSetting(sql.FieldNotIn(FieldCategory, vs...))
}

// CategoryGT applies the GT predicate on the "category" field.
func CategoryGT(v string) predicate.WorldSetting {
	return predicate.WorldSetting(sql.FieldGT(FieldCategory, v))
}

// CategoryGTE applies the GTE predicate on the "category" field.
func CategoryGTE(v string) predicate.WorldSetting {
	return predicate.WorldSetting(sql.FieldGTE(FieldCategory, v))
}

// CategoryLT applies the LT predicate on the "category" field.
func CategoryLT(v string) predicate.WorldSetting {
	return predicate.WorldSetting(sql.FieldLT(FieldCategory, v))
}

// CategoryLTE applies the LTE predicate on the "category" field.
func CategoryLTE(v string) predicate.WorldSetting {
	return predicate.WorldSetting(sql.FieldLTE(FieldCategory, v))
}

// CategoryContains applies the Contains predicate on the "category" field.
func CategoryContains(v string) predicate.WorldSetting {
	return predicate.WorldSetting(sql.FieldContains(FieldCategory, v))
}

// CategoryHasPrefix applies the HasPrefix predicate on the "category" field.
func CategoryHasPrefix(v string) predicate.WorldSetting {
	return predicate.WorldSetting(sql.FieldHasPrefix(FieldCategory, v))
}

// CategoryHasSuffix applies the HasSuffix predicate on the "category" field.
func CategoryHasSuffix(v string) predicate.WorldSetting {
	return predicate.WorldSetting(sql.FieldHasSuffix(FieldCategory, v))
}

// CategoryEqualFold applies the EqualFold predicate on the "category" field.
func CategoryEqualFold(v string) predicate.WorldSetting {
	return predicate.WorldSetting(sql.FieldEqualFold(FieldCategory, v))
}

// CategoryContainsFold applies the ContainsFold predicate on the "category" field.
func CategoryContainsFold(v string) predicate.WorldSetting {
	return predicate.WorldSetting(sql.FieldContainsFold(FieldCategory, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.WorldSetting {
	return predicate.WorldSetting(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.WorldSetting {
	return predicate.WorldSetting(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.WorldSetting {
	return predicate.WorldSetting(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.WorldSetting {
	return predicate.WorldSetting(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.WorldSetting {
	return predicate.WorldSetting(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.WorldSetting {
	return predicate.WorldSetting(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.WorldSetting {
	return predicate.WorldSetting(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.WorldSetting {
	return predicate.WorldSetting(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.WorldSetting {
	return predicate.WorldSetting(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.WorldSetting {
	return predicate.WorldSetting(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.WorldSetting {
	return predicate.WorldSetting(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.WorldSetting {
	return predicate.WorldSetting(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.WorldSetting {
	return predicate.WorldSetting(sql.FieldContainsFold(FieldName, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.WorldSetting {
	return predicate.WorldSetting(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.WorldSetting {
	return predicate.WorldSetting(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.WorldSetting {
	return predicate.WorldSetting(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.WorldSetting {
	return predicate.WorldSetting(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.WorldSetting {
	return predicate.WorldSetting(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.WorldSetting {
	return predicate.WorldSetting(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.WorldSetting {
	return predicate.WorldSetting(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.WorldSetting {
	return predicate.WorldSetting(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.WorldSetting {
	return predicate.WorldSetting(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.WorldSetting {
	return predicate.WorldSetting(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.WorldSetting {
	return predicate.WorldSetting(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.WorldSetting {
	return predicate.WorldSetting(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.WorldSetting {
	return predicate.WorldSetting(sql.FieldContainsFold(FieldDescription, v))
}

// CurrentStateEQ applies the EQ predicate on the "current_state" field.
func CurrentStateEQ(v string) predicate.WorldSetting {
	return predicate.WorldSetting(sql.FieldEQ(FieldCurrentState, v))
}

// CurrentStateNEQ applies the NEQ predicate on the "current_state" field.
func CurrentStateNEQ(v string) predicate.WorldSetting {
	return predicate.WorldSetting(sql.FieldNEQ(FieldCurrentState, v))
}

// CurrentStateIn applies the In predicate on the "current_state" field.
func CurrentStateIn(vs ...string) predicate.WorldSetting {
	return predicate.WorldSetting(sql.FieldIn(FieldCurrentState, vs...))
}

// CurrentStateNotIn applies the NotIn predicate on the "current_state" field.
func CurrentStateNotIn(vs ...string) predicate.WorldSetting {
	return predicate.WorldSetting(sql.FieldNotIn(FieldCurrentState, vs...))
}

// CurrentStateGT applies the GT predicate on the "current_state" field.
func CurrentStateGT(v string) predicate.WorldSetting {
	return predicate.WorldSetting(sql.FieldGT(FieldCurrentState, v))
}

// CurrentStateGTE applies the GTE predicate on the "current_state" field.
func CurrentStateGTE(v string) predicate.WorldSetting {
	return predicate.WorldSetting(sql.FieldGTE(FieldCurrentState, v))
}

// CurrentStateLT applies the LT predicate on the "current_state" field.
func CurrentStateLT(v string) predicate.WorldSetting {
	return predicate.WorldSetting(sql.FieldLT(FieldCurrentState, v))
}

// CurrentStateLTE applies the LTE predicate on the "current_state" field.
func CurrentStateLTE(v string) predicate.WorldSetting {
	return predicate.WorldSetting(sql.FieldLTE(FieldCurrentState, v))
}

// CurrentStateContains applies the Contains predicate on the "current_state" field.
func CurrentStateContains(v string) predicate.WorldSetting {
	return predicate.WorldSetting(sql.FieldContains(FieldCurrentState, v))
}

// CurrentStateHasPrefix applies the HasPrefix predicate on the "current_state" field.
func CurrentStateHasPrefix(v string) predicate.WorldSetting {
	return predicate.WorldSetting(sql.FieldHasPrefix(FieldCurrentState, v))
}

// CurrentStateHasSuffix applies the HasSuffix predicate on the "current_state" field.
func CurrentStateHasSuffix(v string) predicate.WorldSetting {
	return predicate.WorldSetting(sql.FieldHasSuffix(FieldCurrentState, v))
}

// CurrentStateEqualFold applies the EqualFold predicate on the "current_state" field.
func CurrentStateEqualFold(v string) predicate.WorldSetting {
	return predicate.WorldSetting(sql.FieldEqualFold(FieldCurrentState, v))
}

// CurrentStateContainsFold applies the ContainsFold predicate on the "current_state" field.
func CurrentStateContainsFold(v string) predicate.WorldSetting {
	return predicate.WorldSetting(sql.FieldContainsFold(FieldCurrentState, v))
}

// StateVersionedEQ applies the EQ predicate on the "state_versioned" field.
func StateVersionedEQ(v bool) predicate.WorldSetting {
	return predicate.WorldSetting(sql.FieldEQ(FieldStateVersioned, v))
}

// StateVersionedNEQ applies the NEQ predicate on the "state_versioned" field.
func StateVersionedNEQ(v bool) predicate.WorldSetting {
	return predicate.WorldSetting(sql.FieldNEQ(FieldStateVersioned, v))
}

// MetadataIsNil applies the IsNil predicate on the "metadata" field.
func MetadataIsNil() predicate.WorldSetting {
	return predicate.WorldSetting(sql.FieldIsNull(FieldMetadata))
}

// MetadataNotNil applies the NotNil predicate on the "metadata" field.
func MetadataNotNil() predicate.WorldSetting {
	return predicate.WorldSetting(sql.FieldNotNull(FieldMetadata))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.WorldSetting {
	return predicate.WorldSetting(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.WorldSetting {
	return predicate.WorldSetting(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.WorldSetting {
	return predicate.WorldSetting(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.WorldSetting {
	return predicate.WorldSetting(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.WorldSetting {
	return predicate.WorldSetting(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.WorldSetting {
	return predicate.WorldSetting(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.WorldSetting {
	return predicate.WorldSetting(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.WorldSetting {
	return predicate.WorldSetting(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.WorldSetting {
	return predicate.WorldSetting(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.WorldSetting {
	return predicate.WorldSetting(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.WorldSetting {
	return predicate.WorldSetting(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.WorldSetting {
	return predicate.WorldSetting(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.WorldSetting {
	return predicate.WorldSetting(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.WorldSetting {
	return predicate.WorldSetting(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.WorldSetting {
	return predicate.WorldSetting(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.WorldSetting {
	return predicate.WorldSetting(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasStateVersions applies the HasEdge predicate on the "state_versions" edge.
func HasStateVersions() predicate.WorldSetting {
	return predicate.WorldSetting(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, StateVersionsTable, StateVersionsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasStateVersionsWith applies the HasEdge predicate on the "state_versions" edge with a given conditions (other predicates).
func HasStateVersionsWith(preds ...predicate.WorldStateVersion) predicate.WorldSetting {
	return predicate.WorldSetting(func(s *sql.Selector) {
		step := newStateVersionsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.WorldSetting) predicate.WorldSetting {
	return predicate.WorldSetting(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.WorldSetting) predicate.WorldSetting {
	return predicate.WorldSetting(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.WorldSetting) predicate.WorldSetting {
	return predicate.WorldSetting(sql.NotPredicates(p))
}
