// Code generated by ent, DO NOT EDIT.

package relationshipstateversion

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the relationshipstateversion type in the database.
	Label = "relationship_state_version"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldChapterID holds the string denoting the chapter_id field in the database.
	FieldChapterID = "chapter_id"
	// FieldSourceCharacterID holds the string denoting the source_character_id field in the database.
	FieldSourceCharacterID = "source_character_id"
	// FieldTargetCharacterID holds the string denoting the target_character_id field in the database.
	FieldTargetCharacterID = "target_character_id"
	// FieldChapterIndex holds the string denoting the chapter_index field in the database.
	FieldChapterIndex = "chapter_index"
	// FieldGenerationID holds the string denoting the generation_id field in the database.
	FieldGenerationID = "generation_id"
	// FieldRelationType holds the string denoting the relation_type field in the database.
	FieldRelationType = "relation_type"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldActive holds the string denoting the active field in the database.
	FieldActive = "active"
	// FieldOperation holds the string denoting the operation field in the database.
	FieldOperation = "operation"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeChapter holds the string denoting the chapter edge name in mutations.
	EdgeChapter = "chapter"
	// EdgeSourceCharacter holds the string denoting the source_character edge name in mutations.
	EdgeSourceCharacter = "source_character"
	// EdgeTargetCharacter holds the string denoting the target_character edge name in mutations.
	EdgeTargetCharacter = "target_character"
	// Table holds the table name of the relationshipstateversion in the database.
	Table = "relationship_state_versions"
	// ChapterTable is the table that holds the chapter relation/edge.
	ChapterTable = "relationship_state_versions"
	// ChapterInverseTable is the table name for the Chapter entity.
	// It exists in this package in order to avoid circular dependency with the "chapter" package.
	ChapterInverseTable = "chapters"
	// ChapterColumn is the table column denoting the chapter relation/edge.
	ChapterColumn = "chapter_id"
	// SourceCharacterTable is the table that holds the source_character relation/edge.
	SourceCharacterTable = "relationship_state_versions"
	// SourceCharacterInverseTable is the table name for the Character entity.
	// It exists in this package in order to avoid circular dependency with the "character" package.
	SourceCharacterInverseTable = "characters"
	// SourceCharacterColumn is the table column denoting the source_character relation/edge.
	SourceCharacterColumn = "source_character_id"
	// TargetCharacterTable is the table that holds the target_character relation/edge.
	TargetCharacterTable = "relationship_state_versions"
	// TargetCharacterInverseTable is the table name for the Character entity.
	// It exists in this package in order to avoid circular dependency with the "character" package.
	TargetCharacterInverseTable = "characters"
	// TargetCharacterColumn is the table column denoting the target_character relation/edge.
	TargetCharacterColumn = "target_character_id"
)

// Columns holds all SQL columns for relationshipstateversion fields.
var Columns = []string{
	FieldID,
	FieldChapterID,
	FieldSourceCharacterID,
	FieldTargetCharacterID,
	FieldChapterIndex,
	FieldGenerationID,
	FieldRelationType,
	FieldDescription,
	FieldActive,
	FieldOperation,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// ChapterIDValidator is a validator for the "chapter_id" field. It is called by the builders before save.
	ChapterIDValidator func(int) error
	// SourceCharacterIDValidator is a validator for the "source_character_id" field. It is called by the builders before save.
	SourceCharacterIDValidator func(int) error
	// TargetCharacterIDValidator is a validator for the "target_character_id" field. It is called by the builders before save.
	TargetCharacterIDValidator func(int) error
	// ChapterIndexValidator is a validator for the "chapter_index" field. It is called by the builders before save.
	ChapterIndexValidator func(int) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// Operation defines the type for the "operation" enum field.
type Operation string

// Operation values.
const (
	OperationUpsert Operation = "upsert"
	OperationRemove Operation = "remove"
)

func (o Operation) String() string {
	return string(o)
}

// OperationValidator is a validator for the "operation" field enum values. It is called by the builders before save.
func OperationValidator(o Operation) error {
	switch o {
	case OperationUpsert, OperationRemove:
		return nil
	default:
		return fmt.Errorf("relationshipstateversion: invalid enum value for operation field: %q", o)
	}
}

// OrderOption defines the ordering options for the RelationshipStateVersion queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByChapterID orders the results by the chapter_id field.
func ByChapterID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChapterID, opts...).ToFunc()
}

// BySourceCharacterID orders the results by the source_character_id field.
func BySourceCharacterID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceCharacterID, opts...).ToFunc()
}

// ByTargetCharacterID orders the results by the target_character_id field.
func ByTargetCharacterID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTargetCharacterID, opts...).ToFunc()
}

// ByChapterIndex orders the results by the chapter_index field.
func ByChapterIndex(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChapterIndex, opts...).ToFunc()
}

// ByGenerationID orders the results by the generation_id field.
func ByGenerationID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGenerationID, opts...).ToFunc()
}

// ByRelationType orders the results by the relation_type field.
func ByRelationType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRelationType, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByActive orders the results by the active field.
func ByActive(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActive, opts...).ToFunc()
}

// ByOperation orders the results by the operation field.
func ByOperation(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOperation, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByChapterField orders the results by chapter field.
func ByChapterField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newChapterStep(), sql.OrderByField(field, opts...))
	}
}

// BySourceCharacterField orders the results by source_character field.
func BySourceCharacterField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSourceCharacterStep(), sql.OrderByField(field, opts...))
	}
}

// ByTargetCharacterField orders the results by target_character field.
func ByTargetCharacterField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTargetCharacterStep(), sql.OrderByField(field, opts...))
	}
}
func newChapterStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ChapterInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ChapterTable, ChapterColumn),
	)
}
func newSourceCharacterStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SourceCharacterInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, SourceCharacterTable, SourceCharacterColumn),
	)
}
func newTargetCharacterStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TargetCharacterInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, TargetCharacterTable, TargetCharacterColumn),
	)
}
