// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ai-novel/studio/ent/chapterderivedtask"
	"github.com/ai-novel/studio/ent/predicate"
)

// ChapterDerivedTaskDelete is the builder for deleting a ChapterDerivedTask entity.
type ChapterDerivedTaskDelete struct {
	config
	hooks    []Hook
	mutation *ChapterDerivedTaskMutation
}

// Where appends a list predicates to the ChapterDerivedTaskDelete builder.
func (_d *ChapterDerivedTaskDelete) Where(ps ...predicate.ChapterDerivedTask) *ChapterDerivedTaskDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *ChapterDerivedTaskDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ChapterDerivedTaskDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *ChapterDerivedTaskDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(chapterderivedtask.Table, sqlgraph.NewFieldSpec(chapterderivedtask.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// ChapterDerivedTaskDeleteOne is the builder for deleting a single ChapterDerivedTask entity.
type ChapterDerivedTaskDeleteOne struct {
	_d *ChapterDerivedTaskDelete
}

// Where appends a list predicates to the ChapterDerivedTaskDelete builder.
func (_d *ChapterDerivedTaskDeleteOne) Where(ps ...predicate.ChapterDerivedTask) *ChapterDerivedTaskDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *ChapterDerivedTaskDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{chapterderivedtask.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ChapterDerivedTaskDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
