// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/ai-novel/studio/ent/chapter"
	"github.com/ai-novel/studio/ent/character"
	"github.com/ai-novel/studio/ent/characterstateversion"
)

// CharacterStateVersion is the model entity for the CharacterStateVersion schema.
type CharacterStateVersion struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CharacterID holds the value of the "character_id" field.
	CharacterID int `json:"character_id,omitempty"`
	// ChapterID holds the value of the "chapter_id" field.
	ChapterID int `json:"chapter_id,omitempty"`
	// ChapterIndex holds the value of the "chapter_index" field.
	ChapterIndex int `json:"chapter_index,omitempty"`
	// GenerationID holds the value of the "generation_id" field.
	GenerationID string `json:"generation_id,omitempty"`
	// CurrentStatus holds the value of the "current_status" field.
	CurrentStatus string `json:"current_status,omitempty"`
	// Valid holds the value of the "valid" field.
	Valid bool `json:"valid,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the CharacterStateVersionQuery when eager-loading is set.
	Edges        CharacterStateVersionEdges `json:"edges"`
	selectValues sql.SelectValues
}

// CharacterStateVersionEdges holds the relations/edges for other nodes in the graph.
type CharacterStateVersionEdges struct {
	// Chapter holds the value of the chapter edge.
	Chapter *Chapter `json:"chapter,omitempty"`
	// Character holds the value of the character edge.
	Character *Character `json:"character,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// ChapterOrErr returns the Chapter value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e CharacterStateVersionEdges) ChapterOrErr() (*Chapter, error) {
	if e.Chapter != nil {
		return e.Chapter, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: chapter.Label}
	}
	return nil, &NotLoadedError{edge: "chapter"}
}

// CharacterOrErr returns the Character value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e CharacterStateVersionEdges) CharacterOrErr() (*Character, error) {
	if e.Character != nil {
		return e.Character, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: character.Label}
	}
	return nil, &NotLoadedError{edge: "character"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CharacterStateVersion) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case characterstateversion.FieldValid:
			values[i] = new(sql.NullBool)
		case characterstateversion.FieldID, characterstateversion.FieldCharacterID, characterstateversion.FieldChapterID, characterstateversion.FieldChapterIndex:
			values[i] = new(sql.NullInt64)
		case characterstateversion.FieldGenerationID, characterstateversion.FieldCurrentStatus:
			values[i] = new(sql.NullString)
		case characterstateversion.FieldCreatedAt, characterstateversion.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CharacterStateVersion fields.
func (_m *CharacterStateVersion) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case characterstateversion.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case characterstateversion.FieldCharacterID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field character_id", values[i])
			} else if value.Valid {
				_m.CharacterID = int(value.Int64)
			}
		case characterstateversion.FieldChapterID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field chapter_id", values[i])
			} else if value.Valid {
				_m.ChapterID = int(value.Int64)
			}
		case characterstateversion.FieldChapterIndex:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field chapter_index", values[i])
			} else if value.Valid {
				_m.ChapterIndex = int(value.Int64)
			}
		case characterstateversion.FieldGenerationID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field generation_id", values[i])
			} else if value.Valid {
				_m.GenerationID = value.String
			}
		case characterstateversion.FieldCurrentStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field current_status", values[i])
			} else if value.Valid {
				_m.CurrentStatus = value.String
			}
		case characterstateversion.FieldValid:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field valid", values[i])
			} else if value.Valid {
				_m.Valid = value.Bool
			}
		case characterstateversion.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case characterstateversion.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the CharacterStateVersion.
// This includes values selected through modifiers, order, etc.
func (_m *CharacterStateVersion) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryChapter queries the "chapter" edge of the CharacterStateVersion entity.
func (_m *CharacterStateVersion) QueryChapter() *ChapterQuery {
	return NewCharacterStateVersionClient(_m.config).QueryChapter(_m)
}

// QueryCharacter queries the "character" edge of the CharacterStateVersion entity.
func (_m *CharacterStateVersion) QueryCharacter() *CharacterQuery {
	return NewCharacterStateVersionClient(_m.config).QueryCharacter(_m)
}

// Update returns a builder for updating this CharacterStateVersion.
// Note that you need to call CharacterStateVersion.Unwrap() before calling this method if this CharacterStateVersion
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *CharacterStateVersion) Update() *CharacterStateVersionUpdateOne {
	return NewCharacterStateVersionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the CharacterStateVersion entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *CharacterStateVersion) Unwrap() *CharacterStateVersion {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: CharacterStateVersion is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *CharacterStateVersion) String() string {
	var builder strings.Builder
	builder.WriteString("CharacterStateVersion(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("character_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.CharacterID))
	builder.WriteString(", ")
	builder.WriteString("chapter_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ChapterID))
	builder.WriteString(", ")
	builder.WriteString("chapter_index=")
	builder.WriteString(fmt.Sprintf("%v", _m.ChapterIndex))
	builder.WriteString(", ")
	builder.WriteString("generation_id=")
	builder.WriteString(_m.GenerationID)
	builder.WriteString(", ")
	builder.WriteString("current_status=")
	builder.WriteString(_m.CurrentStatus)
	builder.WriteString(", ")
	builder.WriteString("valid=")
	builder.WriteString(fmt.Sprintf("%v", _m.Valid))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// CharacterStateVersions is a parsable slice of CharacterStateVersion.
type CharacterStateVersions []*CharacterStateVersion
