// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ai-novel/studio/ent/character"
	"github.com/ai-novel/studio/ent/characterstateversion"
	"github.com/ai-novel/studio/ent/relationship"
	"github.com/ai-novel/studio/ent/relationshipstateversion"
)

// CharacterCreate is the builder for creating a Character entity.
type CharacterCreate struct {
	config
	mutation *CharacterMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetNovelID sets the "novel_id" field.
func (_c *CharacterCreate) SetNovelID(v string) *CharacterCreate {
	_c.mutation.SetNovelID(v)
	return _c
}

// SetName sets the "name" field.
func (_c *CharacterCreate) SetName(v string) *CharacterCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetGender sets the "gender" field.
func (_c *CharacterCreate) SetGender(v string) *CharacterCreate {
	_c.mutation.SetGender(v)
	return _c
}

// SetNillableGender sets the "gender" field if the given value is not nil.
func (_c *CharacterCreate) SetNillableGender(v *string) *CharacterCreate {
	if v != nil {
		_c.SetGender(*v)
	}
	return _c
}

// SetAge sets the "age" field.
func (_c *CharacterCreate) SetAge(v int) *CharacterCreate {
	_c.mutation.SetAge(v)
	return _c
}

// SetNillableAge sets the "age" field if the given value is not nil.
func (_c *CharacterCreate) SetNillableAge(v *int) *CharacterCreate {
	if v != nil {
		_c.SetAge(*v)
	}
	return _c
}

// SetAppearance sets the "appearance" field.
func (_c *CharacterCreate) SetAppearance(v string) *CharacterCreate {
	_c.mutation.SetAppearance(v)
	return _c
}

// SetNillableAppearance sets the "appearance" field if the given value is not nil.
func (_c *CharacterCreate) SetNillableAppearance(v *string) *CharacterCreate {
	if v != nil {
		_c.SetAppearance(*v)
	}
	return _c
}

// SetPersonality sets the "personality" field.
func (_c *CharacterCreate) SetPersonality(v string) *CharacterCreate {
	_c.mutation.SetPersonality(v)
	return _c
}

// SetNillablePersonality sets the "personality" field if the given value is not nil.
func (_c *CharacterCreate) SetNillablePersonality(v *string) *CharacterCreate {
	if v != nil {
		_c.SetPersonality(*v)
	}
	return _c
}

// SetBackground sets the "background" field.
func (_c *CharacterCreate) SetBackground(v string) *CharacterCreate {
	_c.mutation.SetBackground(v)
	return _c
}

// SetNillableBackground sets the "background" field if the given value is not nil.
func (_c *CharacterCreate) SetNillableBackground(v *string) *CharacterCreate {
	if v != nil {
		_c.SetBackground(*v)
	}
	return _c
}

// SetCurrentStatus sets the "current_status" field.
func (_c *CharacterCreate) SetCurrentStatus(v string) *CharacterCreate {
	_c.mutation.SetCurrentStatus(v)
	return _c
}

// SetNillableCurrentStatus sets the "current_status" field if the given value is not nil.
func (_c *CharacterCreate) SetNillableCurrentStatus(v *string) *CharacterCreate {
	if v != nil {
		_c.SetCurrentStatus(*v)
	}
	return _c
}

// SetStateVersioned sets the "state_versioned" field.
func (_c *CharacterCreate) SetStateVersioned(v bool) *CharacterCreate {
	_c.mutation.SetStateVersioned(v)
	return _c
}

// SetNillableStateVersioned sets the "state_versioned" field if the given value is not nil.
func (_c *CharacterCreate) SetNillableStateVersioned(v *bool) *CharacterCreate {
	if v != nil {
		_c.SetStateVersioned(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *CharacterCreate) SetCreatedAt(v time.Time) *CharacterCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *CharacterCreate) SetNillableCreatedAt(v *time.Time) *CharacterCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *CharacterCreate) SetUpdatedAt(v time.Time) *CharacterCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *CharacterCreate) SetNillableUpdatedAt(v *time.Time) *CharacterCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// AddRelationshipIDs adds the "relationships" edge to the Relationship entity by IDs.
func (_c *CharacterCreate) AddRelationshipIDs(ids ...int) *CharacterCreate {
	_c.mutation.AddRelationshipIDs(ids...)
	return _c
}

// AddRelationships adds the "relationships" edges to the Relationship entity.
func (_c *CharacterCreate) AddRelationships(v ...*Relationship) *CharacterCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddRelationshipIDs(ids...)
}

// AddStateVersionIDs adds the "state_versions" edge to the CharacterStateVersion entity by IDs.
func (_c *CharacterCreate) AddStateVersionIDs(ids ...int) *CharacterCreate {
	_c.mutation.AddStateVersionIDs(ids...)
	return _c
}

// AddStateVersions adds the "state_versions" edges to the CharacterStateVersion entity.
func (_c *CharacterCreate) AddStateVersions(v ...*CharacterStateVersion) *CharacterCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddStateVersionIDs(ids...)
}

// AddSourceRelationshipStateVersionIDs adds the "source_relationship_state_versions" edge to the RelationshipStateVersion entity by IDs.
func (_c *CharacterCreate) AddSourceRelationshipStateVersionIDs(ids ...int) *CharacterCreate {
	_c.mutation.AddSourceRelationshipStateVersionIDs(ids...)
	return _c
}

// AddSourceRelationshipStateVersions adds the "source_relationship_state_versions" edges to the RelationshipStateVersion entity.
func (_c *CharacterCreate) AddSourceRelationshipStateVersions(v ...*RelationshipStateVersion) *CharacterCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddSourceRelationshipStateVersionIDs(ids...)
}

// AddTargetRelationshipStateVersionIDs adds the "target_relationship_state_versions" edge to the RelationshipStateVersion entity by IDs.
func (_c *CharacterCreate) AddTargetRelationshipStateVersionIDs(ids ...int) *CharacterCreate {
	_c.mutation.AddTargetRelationshipStateVersionIDs(ids...)
	return _c
}

// AddTargetRelationshipStateVersions adds the "target_relationship_state_versions" edges to the RelationshipStateVersion entity.
func (_c *CharacterCreate) AddTargetRelationshipStateVersions(v ...*RelationshipStateVersion) *CharacterCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddTargetRelationshipStateVersionIDs(ids...)
}

// Mutation returns the CharacterMutation object of the builder.
func (_c *CharacterCreate) Mutation() *CharacterMutation {
	return _c.mutation
}

// Save creates the Character in the database.
func (_c *CharacterCreate) Save(ctx context.Context) (*Character, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CharacterCreate) SaveX(ctx context.Context) *Character {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CharacterCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CharacterCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CharacterCreate) defaults() {
	if _, ok := _c.mutation.StateVersioned(); !ok {
		v := character.DefaultStateVersioned
		_c.mutation.SetStateVersioned(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := character.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := character.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CharacterCreate) check() error {
	if _, ok := _c.mutation.NovelID(); !ok {
		return &ValidationError{Name: "novel_id", err: errors.New(`ent: missing required field "Character.novel_id"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Character.name"`)}
	}
	if _, ok := _c.mutation.StateVersioned(); !ok {
		return &ValidationError{Name: "state_versioned", err: errors.New(`ent: missing required field "Character.state_versioned"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Character.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Character.updated_at"`)}
	}
	return nil
}

func (_c *CharacterCreate) sqlSave(ctx context.Context) (*Character, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CharacterCreate) createSpec() (*Character, *sqlgraph.CreateSpec) {
	var (
		_node = &Character{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(character.Table, sqlgraph.NewFieldSpec(character.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.NovelID(); ok {
		_spec.SetField(character.FieldNovelID, field.TypeString, value)
		_node.NovelID = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(character.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Gender(); ok {
		_spec.SetField(character.FieldGender, field.TypeString, value)
		_node.Gender = value
	}
	if value, ok := _c.mutation.Age(); ok {
		_spec.SetField(character.FieldAge, field.TypeInt, value)
		_node.Age = value
	}
	if value, ok := _c.mutation.Appearance(); ok {
		_spec.SetField(character.FieldAppearance, field.TypeString, value)
		_node.Appearance = value
	}
	if value, ok := _c.mutation.Personality(); ok {
		_spec.SetField(character.FieldPersonality, field.TypeString, value)
		_node.Personality = value
	}
	if value, ok := _c.mutation.Background(); ok {
		_spec.SetField(character.FieldBackground, field.TypeString, value)
		_node.Background = value
	}
	if value, ok := _c.mutation.CurrentStatus(); ok {
		_spec.SetField(character.FieldCurrentStatus, field.TypeString, value)
		_node.CurrentStatus = value
	}
	if value, ok := _c.mutation.StateVersioned(); ok {
		_spec.SetField(character.FieldStateVersioned, field.TypeBool, value)
		_node.StateVersioned = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(character.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(character.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.RelationshipsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   character.RelationshipsTable,
			Columns: []string{character.RelationshipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(relationship.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.StateVersionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   character.StateVersionsTable,
			Columns: []string{character.StateVersionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(characterstateversion.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.SourceRelationshipStateVersionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   character.SourceRelationshipStateVersionsTable,
			Columns: []string{character.SourceRelationshipStateVersionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(relationshipstateversion.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.TargetRelationshipStateVersionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   character.TargetRelationshipStateVersionsTable,
			Columns: []string{character.TargetRelationshipStateVersionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(relationshipstateversion.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Character.Create().
//		SetNovelID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CharacterUpsert) {
//			SetNovelID(v+v).
//		}).
//		Exec(ctx)
func (_c *CharacterCreate) OnConflict(opts ...sql.ConflictOption) *CharacterUpsertOne {
	_c.conflict = opts
	return &CharacterUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Character.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CharacterCreate) OnConflictColumns(columns ...string) *CharacterUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CharacterUpsertOne{
		create: _c,
	}
}

type (
	// CharacterUpsertOne is the builder for "upsert"-ing
	//  one Character node.
	CharacterUpsertOne struct {
		create *CharacterCreate
	}

	// CharacterUpsert is the "OnConflict" setter.
	CharacterUpsert struct {
		*sql.UpdateSet
	}
)

// SetNovelID sets the "novel_id" field.
func (u *CharacterUpsert) SetNovelID(v string) *CharacterUpsert {
	u.Set(character.FieldNovelID, v)
	return u
}

// UpdateNovelID sets the "novel_id" field to the value that was provided on create.
func (u *CharacterUpsert) UpdateNovelID() *CharacterUpsert {
	u.SetExcluded(character.FieldNovelID)
	return u
}

// SetName sets the "name" field.
func (u *CharacterUpsert) SetName(v string) *CharacterUpsert {
	u.Set(character.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *CharacterUpsert) UpdateName() *CharacterUpsert {
	u.SetExcluded(character.FieldName)
	return u
}

// SetGender sets the "gender" field.
func (u *CharacterUpsert) SetGender(v string) *CharacterUpsert {
	u.Set(character.FieldGender, v)
	return u
}

// UpdateGender sets the "gender" field to the value that was provided on create.
func (u *CharacterUpsert) UpdateGender() *CharacterUpsert {
	u.SetExcluded(character.FieldGender)
	return u
}

// ClearGender clears the value of the "gender" field.
func (u *CharacterUpsert) ClearGender() *CharacterUpsert {
	u.SetNull(character.FieldGender)
	return u
}

// SetAge sets the "age" field.
func (u *CharacterUpsert) SetAge(v int) *CharacterUpsert {
	u.Set(character.FieldAge, v)
	return u
}

// UpdateAge sets the "age" field to the value that was provided on create.
func (u *CharacterUpsert) UpdateAge() *CharacterUpsert {
	u.SetExcluded(character.FieldAge)
	return u
}

// AddAge adds v to the "age" field.
func (u *CharacterUpsert) AddAge(v int) *CharacterUpsert {
	u.Add(character.FieldAge, v)
	return u
}

// ClearAge clears the value of the "age" field.
func (u *CharacterUpsert) ClearAge() *CharacterUpsert {
	u.SetNull(character.FieldAge)
	return u
}

// SetAppearance sets the "appearance" field.
func (u *CharacterUpsert) SetAppearance(v string) *CharacterUpsert {
	u.Set(character.FieldAppearance, v)
	return u
}

// UpdateAppearance sets the "appearance" field to the value that was provided on create.
func (u *CharacterUpsert) UpdateAppearance() *CharacterUpsert {
	u.SetExcluded(character.FieldAppearance)
	return u
}

// ClearAppearance clears the value of the "appearance" field.
func (u *CharacterUpsert) ClearAppearance() *CharacterUpsert {
	u.SetNull(character.FieldAppearance)
	return u
}

// SetPersonality sets the "personality" field.
func (u *CharacterUpsert) SetPersonality(v string) *CharacterUpsert {
	u.Set(character.FieldPersonality, v)
	return u
}

// UpdatePersonality sets the "personality" field to the value that was provided on create.
func (u *CharacterUpsert) UpdatePersonality() *CharacterUpsert {
	u.SetExcluded(character.FieldPersonality)
	return u
}

// ClearPersonality clears the value of the "personality" field.
func (u *CharacterUpsert) ClearPersonality() *CharacterUpsert {
	u.SetNull(character.FieldPersonality)
	return u
}

// SetBackground sets the "background" field.
func (u *CharacterUpsert) SetBackground(v string) *CharacterUpsert {
	u.Set(character.FieldBackground, v)
	return u
}

// UpdateBackground sets the "background" field to the value that was provided on create.
func (u *CharacterUpsert) UpdateBackground() *CharacterUpsert {
	u.SetExcluded(character.FieldBackground)
	return u
}

// ClearBackground clears the value of the "background" field.
func (u *CharacterUpsert) ClearBackground() *CharacterUpsert {
	u.SetNull(character.FieldBackground)
	return u
}

// SetCurrentStatus sets the "current_status" field.
func (u *CharacterUpsert) SetCurrentStatus(v string) *CharacterUpsert {
	u.Set(character.FieldCurrentStatus, v)
	return u
}

// UpdateCurrentStatus sets the "current_status" field to the value that was provided on create.
func (u *CharacterUpsert) UpdateCurrentStatus() *CharacterUpsert {
	u.SetExcluded(character.FieldCurrentStatus)
	return u
}

// ClearCurrentStatus clears the value of the "current_status" field.
func (u *CharacterUpsert) ClearCurrentStatus() *CharacterUpsert {
	u.SetNull(character.FieldCurrentStatus)
	return u
}

// SetStateVersioned sets the "state_versioned" field.
func (u *CharacterUpsert) SetStateVersioned(v bool) *CharacterUpsert {
	u.Set(character.FieldStateVersioned, v)
	return u
}

// UpdateStateVersioned sets the "state_versioned" field to the value that was provided on create.
func (u *CharacterUpsert) UpdateStateVersioned() *CharacterUpsert {
	u.SetExcluded(character.FieldStateVersioned)
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *CharacterUpsert) SetCreatedAt(v time.Time) *CharacterUpsert {
	u.Set(character.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *CharacterUpsert) UpdateCreatedAt() *CharacterUpsert {
	u.SetExcluded(character.FieldCreatedAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CharacterUpsert) SetUpdatedAt(v time.Time) *CharacterUpsert {
	u.Set(character.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CharacterUpsert) UpdateUpdatedAt() *CharacterUpsert {
	u.SetExcluded(character.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Character.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CharacterUpsertOne) UpdateNewValues() *CharacterUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Character.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *CharacterUpsertOne) Ignore() *CharacterUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CharacterUpsertOne) DoNothing() *CharacterUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CharacterCreate.OnConflict
// documentation for more info.
func (u *CharacterUpsertOne) Update(set func(*CharacterUpsert)) *CharacterUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CharacterUpsert{UpdateSet: update})
	}))
	return u
}

// SetNovelID sets the "novel_id" field.
func (u *CharacterUpsertOne) SetNovelID(v string) *CharacterUpsertOne {
	return u.Update(func(s *CharacterUpsert) {
		s.SetNovelID(v)
	})
}

// UpdateNovelID sets the "novel_id" field to the value that was provided on create.
func (u *CharacterUpsertOne) UpdateNovelID() *CharacterUpsertOne {
	return u.Update(func(s *CharacterUpsert) {
		s.UpdateNovelID()
	})
}

// SetName sets the "name" field.
func (u *CharacterUpsertOne) SetName(v string) *CharacterUpsertOne {
	return u.Update(func(s *CharacterUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *CharacterUpsertOne) UpdateName() *CharacterUpsertOne {
	return u.Update(func(s *CharacterUpsert) {
		s.UpdateName()
	})
}

// SetGender sets the "gender" field.
func (u *CharacterUpsertOne) SetGender(v string) *CharacterUpsertOne {
	return u.Update(func(s *CharacterUpsert) {
		s.SetGender(v)
	})
}

// UpdateGender sets the "gender" field to the value that was provided on create.
func (u *CharacterUpsertOne) UpdateGender() *CharacterUpsertOne {
	return u.Update(func(s *CharacterUpsert) {
		s.UpdateGender()
	})
}

// ClearGender clears the value of the "gender" field.
func (u *CharacterUpsertOne) ClearGender() *CharacterUpsertOne {
	return u.Update(func(s *CharacterUpsert) {
		s.ClearGender()
	})
}

// SetAge sets the "age" field.
func (u *CharacterUpsertOne) SetAge(v int) *CharacterUpsertOne {
	return u.Update(func(s *CharacterUpsert) {
		s.SetAge(v)
	})
}

// AddAge adds v to the "age" field.
func (u *CharacterUpsertOne) AddAge(v int) *CharacterUpsertOne {
	return u.Update(func(s *CharacterUpsert) {
		s.AddAge(v)
	})
}

// UpdateAge sets the "age" field to the value that was provided on create.
func (u *CharacterUpsertOne) UpdateAge() *CharacterUpsertOne {
	return u.Update(func(s *CharacterUpsert) {
		s.UpdateAge()
	})
}

// ClearAge clears the value of the "age" field.
func (u *CharacterUpsertOne) ClearAge() *CharacterUpsertOne {
	return u.Update(func(s *CharacterUpsert) {
		s.ClearAge()
	})
}

// SetAppearance sets the "appearance" field.
func (u *CharacterUpsertOne) SetAppearance(v string) *CharacterUpsertOne {
	return u.Update(func(s *CharacterUpsert) {
		s.SetAppearance(v)
	})
}

// UpdateAppearance sets the "appearance" field to the value that was provided on create.
func (u *CharacterUpsertOne) UpdateAppearance() *CharacterUpsertOne {
	return u.Update(func(s *CharacterUpsert) {
		s.UpdateAppearance()
	})
}

// ClearAppearance clears the value of the "appearance" field.
func (u *CharacterUpsertOne) ClearAppearance() *CharacterUpsertOne {
	return u.Update(func(s *CharacterUpsert) {
		s.ClearAppearance()
	})
}

// SetPersonality sets the "personality" field.
func (u *CharacterUpsertOne) SetPersonality(v string) *CharacterUpsertOne {
	return u.Update(func(s *CharacterUpsert) {
		s.SetPersonality(v)
	})
}

// UpdatePersonality sets the "personality" field to the value that was provided on create.
func (u *CharacterUpsertOne) UpdatePersonality() *CharacterUpsertOne {
	return u.Update(func(s *CharacterUpsert) {
		s.UpdatePersonality()
	})
}

// ClearPersonality clears the value of the "personality" field.
func (u *CharacterUpsertOne) ClearPersonality() *CharacterUpsertOne {
	return u.Update(func(s *CharacterUpsert) {
		s.ClearPersonality()
	})
}

// SetBackground sets the "background" field.
func (u *CharacterUpsertOne) SetBackground(v string) *CharacterUpsertOne {
	return u.Update(func(s *CharacterUpsert) {
		s.SetBackground(v)
	})
}

// UpdateBackground sets the "background" field to the value that was provided on create.
func (u *CharacterUpsertOne) UpdateBackground() *CharacterUpsertOne {
	return u.Update(func(s *CharacterUpsert) {
		s.UpdateBackground()
	})
}

// ClearBackground clears the value of the "background" field.
func (u *CharacterUpsertOne) ClearBackground() *CharacterUpsertOne {
	return u.Update(func(s *CharacterUpsert) {
		s.ClearBackground()
	})
}

// SetCurrentStatus sets the "current_status" field.
func (u *CharacterUpsertOne) SetCurrentStatus(v string) *CharacterUpsertOne {
	return u.Update(func(s *CharacterUpsert) {
		s.SetCurrentStatus(v)
	})
}

// UpdateCurrentStatus sets the "current_status" field to the value that was provided on create.
func (u *CharacterUpsertOne) UpdateCurrentStatus() *CharacterUpsertOne {
	return u.Update(func(s *CharacterUpsert) {
		s.UpdateCurrentStatus()
	})
}

// ClearCurrentStatus clears the value of the "current_status" field.
func (u *CharacterUpsertOne) ClearCurrentStatus() *CharacterUpsertOne {
	return u.Update(func(s *CharacterUpsert) {
		s.ClearCurrentStatus()
	})
}

// SetStateVersioned sets the "state_versioned" field.
func (u *CharacterUpsertOne) SetStateVersioned(v bool) *CharacterUpsertOne {
	return u.Update(func(s *CharacterUpsert) {
		s.SetStateVersioned(v)
	})
}

// UpdateStateVersioned sets the "state_versioned" field to the value that was provided on create.
func (u *CharacterUpsertOne) UpdateStateVersioned() *CharacterUpsertOne {
	return u.Update(func(s *CharacterUpsert) {
		s.UpdateStateVersioned()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *CharacterUpsertOne) SetCreatedAt(v time.Time) *CharacterUpsertOne {
	return u.Update(func(s *CharacterUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *CharacterUpsertOne) UpdateCreatedAt() *CharacterUpsertOne {
	return u.Update(func(s *CharacterUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CharacterUpsertOne) SetUpdatedAt(v time.Time) *CharacterUpsertOne {
	return u.Update(func(s *CharacterUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CharacterUpsertOne) UpdateUpdatedAt() *CharacterUpsertOne {
	return u.Update(func(s *CharacterUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *CharacterUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CharacterCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CharacterUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *CharacterUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *CharacterUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// CharacterCreateBulk is the builder for creating many Character entities in bulk.
type CharacterCreateBulk struct {
	config
	err      error
	builders []*CharacterCreate
	conflict []sql.ConflictOption
}

// Save creates the Character entities in the database.
func (_c *CharacterCreateBulk) Save(ctx context.Context) ([]*Character, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Character, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CharacterMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CharacterCreateBulk) SaveX(ctx context.Context) []*Character {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CharacterCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CharacterCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Character.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CharacterUpsert) {
//			SetNovelID(v+v).
//		}).
//		Exec(ctx)
func (_c *CharacterCreateBulk) OnConflict(opts ...sql.ConflictOption) *CharacterUpsertBulk {
	_c.conflict = opts
	return &CharacterUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Character.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CharacterCreateBulk) OnConflictColumns(columns ...string) *CharacterUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CharacterUpsertBulk{
		create: _c,
	}
}

// CharacterUpsertBulk is the builder for "upsert"-ing
// a bulk of Character nodes.
type CharacterUpsertBulk struct {
	create *CharacterCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Character.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CharacterUpsertBulk) UpdateNewValues() *CharacterUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Character.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *CharacterUpsertBulk) Ignore() *CharacterUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CharacterUpsertBulk) DoNothing() *CharacterUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CharacterCreateBulk.OnConflict
// documentation for more info.
func (u *CharacterUpsertBulk) Update(set func(*CharacterUpsert)) *CharacterUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CharacterUpsert{UpdateSet: update})
	}))
	return u
}

// SetNovelID sets the "novel_id" field.
func (u *CharacterUpsertBulk) SetNovelID(v string) *CharacterUpsertBulk {
	return u.Update(func(s *CharacterUpsert) {
		s.SetNovelID(v)
	})
}

// UpdateNovelID sets the "novel_id" field to the value that was provided on create.
func (u *CharacterUpsertBulk) UpdateNovelID() *CharacterUpsertBulk {
	return u.Update(func(s *CharacterUpsert) {
		s.UpdateNovelID()
	})
}

// SetName sets the "name" field.
func (u *CharacterUpsertBulk) SetName(v string) *CharacterUpsertBulk {
	return u.Update(func(s *CharacterUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *CharacterUpsertBulk) UpdateName() *CharacterUpsertBulk {
	return u.Update(func(s *CharacterUpsert) {
		s.UpdateName()
	})
}

// SetGender sets the "gender" field.
func (u *CharacterUpsertBulk) SetGender(v string) *CharacterUpsertBulk {
	return u.Update(func(s *CharacterUpsert) {
		s.SetGender(v)
	})
}

// UpdateGender sets the "gender" field to the value that was provided on create.
func (u *CharacterUpsertBulk) UpdateGender() *CharacterUpsertBulk {
	return u.Update(func(s *CharacterUpsert) {
		s.UpdateGender()
	})
}

// ClearGender clears the value of the "gender" field.
func (u *CharacterUpsertBulk) ClearGender() *CharacterUpsertBulk {
	return u.Update(func(s *CharacterUpsert) {
		s.ClearGender()
	})
}

// SetAge sets the "age" field.
func (u *CharacterUpsertBulk) SetAge(v int) *CharacterUpsertBulk {
	return u.Update(func(s *CharacterUpsert) {
		s.SetAge(v)
	})
}

// AddAge adds v to the "age" field.
func (u *CharacterUpsertBulk) AddAge(v int) *CharacterUpsertBulk {
	return u.Update(func(s *CharacterUpsert) {
		s.AddAge(v)
	})
}

// UpdateAge sets the "age" field to the value that was provided on create.
func (u *CharacterUpsertBulk) UpdateAge() *CharacterUpsertBulk {
	return u.Update(func(s *CharacterUpsert) {
		s.UpdateAge()
	})
}

// ClearAge clears the value of the "age" field.
func (u *CharacterUpsertBulk) ClearAge() *CharacterUpsertBulk {
	return u.Update(func(s *CharacterUpsert) {
		s.ClearAge()
	})
}

// SetAppearance sets the "appearance" field.
func (u *CharacterUpsertBulk) SetAppearance(v string) *CharacterUpsertBulk {
	return u.Update(func(s *CharacterUpsert) {
		s.SetAppearance(v)
	})
}

// UpdateAppearance sets the "appearance" field to the value that was provided on create.
func (u *CharacterUpsertBulk) UpdateAppearance() *CharacterUpsertBulk {
	return u.Update(func(s *CharacterUpsert) {
		s.UpdateAppearance()
	})
}

// ClearAppearance clears the value of the "appearance" field.
func (u *CharacterUpsertBulk) ClearAppearance() *CharacterUpsertBulk {
	return u.Update(func(s *CharacterUpsert) {
		s.ClearAppearance()
	})
}

// SetPersonality sets the "personality" field.
func (u *CharacterUpsertBulk) SetPersonality(v string) *CharacterUpsertBulk {
	return u.Update(func(s *CharacterUpsert) {
		s.SetPersonality(v)
	})
}

// UpdatePersonality sets the "personality" field to the value that was provided on create.
func (u *CharacterUpsertBulk) UpdatePersonality() *CharacterUpsertBulk {
	return u.Update(func(s *CharacterUpsert) {
		s.UpdatePersonality()
	})
}

// ClearPersonality clears the value of the "personality" field.
func (u *CharacterUpsertBulk) ClearPersonality() *CharacterUpsertBulk {
	return u.Update(func(s *CharacterUpsert) {
		s.ClearPersonality()
	})
}

// SetBackground sets the "background" field.
func (u *CharacterUpsertBulk) SetBackground(v string) *CharacterUpsertBulk {
	return u.Update(func(s *CharacterUpsert) {
		s.SetBackground(v)
	})
}

// UpdateBackground sets the "background" field to the value that was provided on create.
func (u *CharacterUpsertBulk) UpdateBackground() *CharacterUpsertBulk {
	return u.Update(func(s *CharacterUpsert) {
		s.UpdateBackground()
	})
}

// ClearBackground clears the value of the "background" field.
func (u *CharacterUpsertBulk) ClearBackground() *CharacterUpsertBulk {
	return u.Update(func(s *CharacterUpsert) {
		s.ClearBackground()
	})
}

// SetCurrentStatus sets the "current_status" field.
func (u *CharacterUpsertBulk) SetCurrentStatus(v string) *CharacterUpsertBulk {
	return u.Update(func(s *CharacterUpsert) {
		s.SetCurrentStatus(v)
	})
}

// UpdateCurrentStatus sets the "current_status" field to the value that was provided on create.
func (u *CharacterUpsertBulk) UpdateCurrentStatus() *CharacterUpsertBulk {
	return u.Update(func(s *CharacterUpsert) {
		s.UpdateCurrentStatus()
	})
}

// ClearCurrentStatus clears the value of the "current_status" field.
func (u *CharacterUpsertBulk) ClearCurrentStatus() *CharacterUpsertBulk {
	return u.Update(func(s *CharacterUpsert) {
		s.ClearCurrentStatus()
	})
}

// SetStateVersioned sets the "state_versioned" field.
func (u *CharacterUpsertBulk) SetStateVersioned(v bool) *CharacterUpsertBulk {
	return u.Update(func(s *CharacterUpsert) {
		s.SetStateVersioned(v)
	})
}

// UpdateStateVersioned sets the "state_versioned" field to the value that was provided on create.
func (u *CharacterUpsertBulk) UpdateStateVersioned() *CharacterUpsertBulk {
	return u.Update(func(s *CharacterUpsert) {
		s.UpdateStateVersioned()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *CharacterUpsertBulk) SetCreatedAt(v time.Time) *CharacterUpsertBulk {
	return u.Update(func(s *CharacterUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *CharacterUpsertBulk) UpdateCreatedAt() *CharacterUpsertBulk {
	return u.Update(func(s *CharacterUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CharacterUpsertBulk) SetUpdatedAt(v time.Time) *CharacterUpsertBulk {
	return u.Update(func(s *CharacterUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CharacterUpsertBulk) UpdateUpdatedAt() *CharacterUpsertBulk {
	return u.Update(func(s *CharacterUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *CharacterUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the CharacterCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CharacterCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CharacterUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
