// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/ai-novel/studio/ent/character"
)

// Character is the model entity for the Character schema.
type Character struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// NovelID holds the value of the "novel_id" field.
	NovelID string `json:"novel_id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Gender holds the value of the "gender" field.
	Gender string `json:"gender,omitempty"`
	// Age holds the value of the "age" field.
	Age int `json:"age,omitempty"`
	// Appearance holds the value of the "appearance" field.
	Appearance string `json:"appearance,omitempty"`
	// Personality holds the value of the "personality" field.
	Personality string `json:"personality,omitempty"`
	// Background holds the value of the "background" field.
	Background string `json:"background,omitempty"`
	// CurrentStatus holds the value of the "current_status" field.
	CurrentStatus string `json:"current_status,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the CharacterQuery when eager-loading is set.
	Edges        CharacterEdges `json:"edges"`
	selectValues sql.SelectValues
}

// CharacterEdges holds the relations/edges for other nodes in the graph.
type CharacterEdges struct {
	// Relationships holds the value of the relationships edge.
	Relationships []*Relationship `json:"relationships,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// RelationshipsOrErr returns the Relationships value or an error if the edge
// was not loaded in eager-loading.
func (e CharacterEdges) RelationshipsOrErr() ([]*Relationship, error) {
	if e.loadedTypes[0] {
		return e.Relationships, nil
	}
	return nil, &NotLoadedError{edge: "relationships"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Character) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case character.FieldID, character.FieldAge:
			values[i] = new(sql.NullInt64)
		case character.FieldNovelID, character.FieldName, character.FieldGender, character.FieldAppearance, character.FieldPersonality, character.FieldBackground, character.FieldCurrentStatus:
			values[i] = new(sql.NullString)
		case character.FieldCreatedAt, character.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Character fields.
func (_m *Character) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case character.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case character.FieldNovelID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field novel_id", values[i])
			} else if value.Valid {
				_m.NovelID = value.String
			}
		case character.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case character.FieldGender:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field gender", values[i])
			} else if value.Valid {
				_m.Gender = value.String
			}
		case character.FieldAge:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field age", values[i])
			} else if value.Valid {
				_m.Age = int(value.Int64)
			}
		case character.FieldAppearance:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field appearance", values[i])
			} else if value.Valid {
				_m.Appearance = value.String
			}
		case character.FieldPersonality:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field personality", values[i])
			} else if value.Valid {
				_m.Personality = value.String
			}
		case character.FieldBackground:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field background", values[i])
			} else if value.Valid {
				_m.Background = value.String
			}
		case character.FieldCurrentStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field current_status", values[i])
			} else if value.Valid {
				_m.CurrentStatus = value.String
			}
		case character.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case character.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Character.
// This includes values selected through modifiers, order, etc.
func (_m *Character) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryRelationships queries the "relationships" edge of the Character entity.
func (_m *Character) QueryRelationships() *RelationshipQuery {
	return NewCharacterClient(_m.config).QueryRelationships(_m)
}

// Update returns a builder for updating this Character.
// Note that you need to call Character.Unwrap() before calling this method if this Character
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Character) Update() *CharacterUpdateOne {
	return NewCharacterClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Character entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Character) Unwrap() *Character {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Character is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Character) String() string {
	var builder strings.Builder
	builder.WriteString("Character(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("novel_id=")
	builder.WriteString(_m.NovelID)
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("gender=")
	builder.WriteString(_m.Gender)
	builder.WriteString(", ")
	builder.WriteString("age=")
	builder.WriteString(fmt.Sprintf("%v", _m.Age))
	builder.WriteString(", ")
	builder.WriteString("appearance=")
	builder.WriteString(_m.Appearance)
	builder.WriteString(", ")
	builder.WriteString("personality=")
	builder.WriteString(_m.Personality)
	builder.WriteString(", ")
	builder.WriteString("background=")
	builder.WriteString(_m.Background)
	builder.WriteString(", ")
	builder.WriteString("current_status=")
	builder.WriteString(_m.CurrentStatus)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Characters is a parsable slice of Character.
type Characters []*Character
