// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ai-novel/studio/ent/character"
	"github.com/ai-novel/studio/ent/predicate"
	"github.com/ai-novel/studio/ent/relationship"
)

// CharacterUpdate is the builder for updating Character entities.
type CharacterUpdate struct {
	config
	hooks    []Hook
	mutation *CharacterMutation
}

// Where appends a list predicates to the CharacterUpdate builder.
func (_u *CharacterUpdate) Where(ps ...predicate.Character) *CharacterUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetNovelID sets the "novel_id" field.
func (_u *CharacterUpdate) SetNovelID(v string) *CharacterUpdate {
	_u.mutation.SetNovelID(v)
	return _u
}

// SetNillableNovelID sets the "novel_id" field if the given value is not nil.
func (_u *CharacterUpdate) SetNillableNovelID(v *string) *CharacterUpdate {
	if v != nil {
		_u.SetNovelID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *CharacterUpdate) SetName(v string) *CharacterUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *CharacterUpdate) SetNillableName(v *string) *CharacterUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetGender sets the "gender" field.
func (_u *CharacterUpdate) SetGender(v string) *CharacterUpdate {
	_u.mutation.SetGender(v)
	return _u
}

// SetNillableGender sets the "gender" field if the given value is not nil.
func (_u *CharacterUpdate) SetNillableGender(v *string) *CharacterUpdate {
	if v != nil {
		_u.SetGender(*v)
	}
	return _u
}

// ClearGender clears the value of the "gender" field.
func (_u *CharacterUpdate) ClearGender() *CharacterUpdate {
	_u.mutation.ClearGender()
	return _u
}

// SetAge sets the "age" field.
func (_u *CharacterUpdate) SetAge(v int) *CharacterUpdate {
	_u.mutation.ResetAge()
	_u.mutation.SetAge(v)
	return _u
}

// SetNillableAge sets the "age" field if the given value is not nil.
func (_u *CharacterUpdate) SetNillableAge(v *int) *CharacterUpdate {
	if v != nil {
		_u.SetAge(*v)
	}
	return _u
}

// AddAge adds value to the "age" field.
func (_u *CharacterUpdate) AddAge(v int) *CharacterUpdate {
	_u.mutation.AddAge(v)
	return _u
}

// ClearAge clears the value of the "age" field.
func (_u *CharacterUpdate) ClearAge() *CharacterUpdate {
	_u.mutation.ClearAge()
	return _u
}

// SetAppearance sets the "appearance" field.
func (_u *CharacterUpdate) SetAppearance(v string) *CharacterUpdate {
	_u.mutation.SetAppearance(v)
	return _u
}

// SetNillableAppearance sets the "appearance" field if the given value is not nil.
func (_u *CharacterUpdate) SetNillableAppearance(v *string) *CharacterUpdate {
	if v != nil {
		_u.SetAppearance(*v)
	}
	return _u
}

// ClearAppearance clears the value of the "appearance" field.
func (_u *CharacterUpdate) ClearAppearance() *CharacterUpdate {
	_u.mutation.ClearAppearance()
	return _u
}

// SetPersonality sets the "personality" field.
func (_u *CharacterUpdate) SetPersonality(v string) *CharacterUpdate {
	_u.mutation.SetPersonality(v)
	return _u
}

// SetNillablePersonality sets the "personality" field if the given value is not nil.
func (_u *CharacterUpdate) SetNillablePersonality(v *string) *CharacterUpdate {
	if v != nil {
		_u.SetPersonality(*v)
	}
	return _u
}

// ClearPersonality clears the value of the "personality" field.
func (_u *CharacterUpdate) ClearPersonality() *CharacterUpdate {
	_u.mutation.ClearPersonality()
	return _u
}

// SetBackground sets the "background" field.
func (_u *CharacterUpdate) SetBackground(v string) *CharacterUpdate {
	_u.mutation.SetBackground(v)
	return _u
}

// SetNillableBackground sets the "background" field if the given value is not nil.
func (_u *CharacterUpdate) SetNillableBackground(v *string) *CharacterUpdate {
	if v != nil {
		_u.SetBackground(*v)
	}
	return _u
}

// ClearBackground clears the value of the "background" field.
func (_u *CharacterUpdate) ClearBackground() *CharacterUpdate {
	_u.mutation.ClearBackground()
	return _u
}

// SetCurrentStatus sets the "current_status" field.
func (_u *CharacterUpdate) SetCurrentStatus(v string) *CharacterUpdate {
	_u.mutation.SetCurrentStatus(v)
	return _u
}

// SetNillableCurrentStatus sets the "current_status" field if the given value is not nil.
func (_u *CharacterUpdate) SetNillableCurrentStatus(v *string) *CharacterUpdate {
	if v != nil {
		_u.SetCurrentStatus(*v)
	}
	return _u
}

// ClearCurrentStatus clears the value of the "current_status" field.
func (_u *CharacterUpdate) ClearCurrentStatus() *CharacterUpdate {
	_u.mutation.ClearCurrentStatus()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *CharacterUpdate) SetCreatedAt(v time.Time) *CharacterUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *CharacterUpdate) SetNillableCreatedAt(v *time.Time) *CharacterUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CharacterUpdate) SetUpdatedAt(v time.Time) *CharacterUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddRelationshipIDs adds the "relationships" edge to the Relationship entity by IDs.
func (_u *CharacterUpdate) AddRelationshipIDs(ids ...int) *CharacterUpdate {
	_u.mutation.AddRelationshipIDs(ids...)
	return _u
}

// AddRelationships adds the "relationships" edges to the Relationship entity.
func (_u *CharacterUpdate) AddRelationships(v ...*Relationship) *CharacterUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRelationshipIDs(ids...)
}

// Mutation returns the CharacterMutation object of the builder.
func (_u *CharacterUpdate) Mutation() *CharacterMutation {
	return _u.mutation
}

// ClearRelationships clears all "relationships" edges to the Relationship entity.
func (_u *CharacterUpdate) ClearRelationships() *CharacterUpdate {
	_u.mutation.ClearRelationships()
	return _u
}

// RemoveRelationshipIDs removes the "relationships" edge to Relationship entities by IDs.
func (_u *CharacterUpdate) RemoveRelationshipIDs(ids ...int) *CharacterUpdate {
	_u.mutation.RemoveRelationshipIDs(ids...)
	return _u
}

// RemoveRelationships removes "relationships" edges to Relationship entities.
func (_u *CharacterUpdate) RemoveRelationships(v ...*Relationship) *CharacterUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRelationshipIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CharacterUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CharacterUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CharacterUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CharacterUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CharacterUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := character.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *CharacterUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(character.Table, character.Columns, sqlgraph.NewFieldSpec(character.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.NovelID(); ok {
		_spec.SetField(character.FieldNovelID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(character.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Gender(); ok {
		_spec.SetField(character.FieldGender, field.TypeString, value)
	}
	if _u.mutation.GenderCleared() {
		_spec.ClearField(character.FieldGender, field.TypeString)
	}
	if value, ok := _u.mutation.Age(); ok {
		_spec.SetField(character.FieldAge, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAge(); ok {
		_spec.AddField(character.FieldAge, field.TypeInt, value)
	}
	if _u.mutation.AgeCleared() {
		_spec.ClearField(character.FieldAge, field.TypeInt)
	}
	if value, ok := _u.mutation.Appearance(); ok {
		_spec.SetField(character.FieldAppearance, field.TypeString, value)
	}
	if _u.mutation.AppearanceCleared() {
		_spec.ClearField(character.FieldAppearance, field.TypeString)
	}
	if value, ok := _u.mutation.Personality(); ok {
		_spec.SetField(character.FieldPersonality, field.TypeString, value)
	}
	if _u.mutation.PersonalityCleared() {
		_spec.ClearField(character.FieldPersonality, field.TypeString)
	}
	if value, ok := _u.mutation.Background(); ok {
		_spec.SetField(character.FieldBackground, field.TypeString, value)
	}
	if _u.mutation.BackgroundCleared() {
		_spec.ClearField(character.FieldBackground, field.TypeString)
	}
	if value, ok := _u.mutation.CurrentStatus(); ok {
		_spec.SetField(character.FieldCurrentStatus, field.TypeString, value)
	}
	if _u.mutation.CurrentStatusCleared() {
		_spec.ClearField(character.FieldCurrentStatus, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(character.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(character.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.RelationshipsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   character.RelationshipsTable,
			Columns: []string{character.RelationshipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(relationship.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRelationshipsIDs(); len(nodes) > 0 && !_u.mutation.RelationshipsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   character.RelationshipsTable,
			Columns: []string{character.RelationshipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(relationship.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RelationshipsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   character.RelationshipsTable,
			Columns: []string{character.RelationshipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(relationship.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{character.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CharacterUpdateOne is the builder for updating a single Character entity.
type CharacterUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CharacterMutation
}

// SetNovelID sets the "novel_id" field.
func (_u *CharacterUpdateOne) SetNovelID(v string) *CharacterUpdateOne {
	_u.mutation.SetNovelID(v)
	return _u
}

// SetNillableNovelID sets the "novel_id" field if the given value is not nil.
func (_u *CharacterUpdateOne) SetNillableNovelID(v *string) *CharacterUpdateOne {
	if v != nil {
		_u.SetNovelID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *CharacterUpdateOne) SetName(v string) *CharacterUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *CharacterUpdateOne) SetNillableName(v *string) *CharacterUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetGender sets the "gender" field.
func (_u *CharacterUpdateOne) SetGender(v string) *CharacterUpdateOne {
	_u.mutation.SetGender(v)
	return _u
}

// SetNillableGender sets the "gender" field if the given value is not nil.
func (_u *CharacterUpdateOne) SetNillableGender(v *string) *CharacterUpdateOne {
	if v != nil {
		_u.SetGender(*v)
	}
	return _u
}

// ClearGender clears the value of the "gender" field.
func (_u *CharacterUpdateOne) ClearGender() *CharacterUpdateOne {
	_u.mutation.ClearGender()
	return _u
}

// SetAge sets the "age" field.
func (_u *CharacterUpdateOne) SetAge(v int) *CharacterUpdateOne {
	_u.mutation.ResetAge()
	_u.mutation.SetAge(v)
	return _u
}

// SetNillableAge sets the "age" field if the given value is not nil.
func (_u *CharacterUpdateOne) SetNillableAge(v *int) *CharacterUpdateOne {
	if v != nil {
		_u.SetAge(*v)
	}
	return _u
}

// AddAge adds value to the "age" field.
func (_u *CharacterUpdateOne) AddAge(v int) *CharacterUpdateOne {
	_u.mutation.AddAge(v)
	return _u
}

// ClearAge clears the value of the "age" field.
func (_u *CharacterUpdateOne) ClearAge() *CharacterUpdateOne {
	_u.mutation.ClearAge()
	return _u
}

// SetAppearance sets the "appearance" field.
func (_u *CharacterUpdateOne) SetAppearance(v string) *CharacterUpdateOne {
	_u.mutation.SetAppearance(v)
	return _u
}

// SetNillableAppearance sets the "appearance" field if the given value is not nil.
func (_u *CharacterUpdateOne) SetNillableAppearance(v *string) *CharacterUpdateOne {
	if v != nil {
		_u.SetAppearance(*v)
	}
	return _u
}

// ClearAppearance clears the value of the "appearance" field.
func (_u *CharacterUpdateOne) ClearAppearance() *CharacterUpdateOne {
	_u.mutation.ClearAppearance()
	return _u
}

// SetPersonality sets the "personality" field.
func (_u *CharacterUpdateOne) SetPersonality(v string) *CharacterUpdateOne {
	_u.mutation.SetPersonality(v)
	return _u
}

// SetNillablePersonality sets the "personality" field if the given value is not nil.
func (_u *CharacterUpdateOne) SetNillablePersonality(v *string) *CharacterUpdateOne {
	if v != nil {
		_u.SetPersonality(*v)
	}
	return _u
}

// ClearPersonality clears the value of the "personality" field.
func (_u *CharacterUpdateOne) ClearPersonality() *CharacterUpdateOne {
	_u.mutation.ClearPersonality()
	return _u
}

// SetBackground sets the "background" field.
func (_u *CharacterUpdateOne) SetBackground(v string) *CharacterUpdateOne {
	_u.mutation.SetBackground(v)
	return _u
}

// SetNillableBackground sets the "background" field if the given value is not nil.
func (_u *CharacterUpdateOne) SetNillableBackground(v *string) *CharacterUpdateOne {
	if v != nil {
		_u.SetBackground(*v)
	}
	return _u
}

// ClearBackground clears the value of the "background" field.
func (_u *CharacterUpdateOne) ClearBackground() *CharacterUpdateOne {
	_u.mutation.ClearBackground()
	return _u
}

// SetCurrentStatus sets the "current_status" field.
func (_u *CharacterUpdateOne) SetCurrentStatus(v string) *CharacterUpdateOne {
	_u.mutation.SetCurrentStatus(v)
	return _u
}

// SetNillableCurrentStatus sets the "current_status" field if the given value is not nil.
func (_u *CharacterUpdateOne) SetNillableCurrentStatus(v *string) *CharacterUpdateOne {
	if v != nil {
		_u.SetCurrentStatus(*v)
	}
	return _u
}

// ClearCurrentStatus clears the value of the "current_status" field.
func (_u *CharacterUpdateOne) ClearCurrentStatus() *CharacterUpdateOne {
	_u.mutation.ClearCurrentStatus()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *CharacterUpdateOne) SetCreatedAt(v time.Time) *CharacterUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *CharacterUpdateOne) SetNillableCreatedAt(v *time.Time) *CharacterUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CharacterUpdateOne) SetUpdatedAt(v time.Time) *CharacterUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddRelationshipIDs adds the "relationships" edge to the Relationship entity by IDs.
func (_u *CharacterUpdateOne) AddRelationshipIDs(ids ...int) *CharacterUpdateOne {
	_u.mutation.AddRelationshipIDs(ids...)
	return _u
}

// AddRelationships adds the "relationships" edges to the Relationship entity.
func (_u *CharacterUpdateOne) AddRelationships(v ...*Relationship) *CharacterUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRelationshipIDs(ids...)
}

// Mutation returns the CharacterMutation object of the builder.
func (_u *CharacterUpdateOne) Mutation() *CharacterMutation {
	return _u.mutation
}

// ClearRelationships clears all "relationships" edges to the Relationship entity.
func (_u *CharacterUpdateOne) ClearRelationships() *CharacterUpdateOne {
	_u.mutation.ClearRelationships()
	return _u
}

// RemoveRelationshipIDs removes the "relationships" edge to Relationship entities by IDs.
func (_u *CharacterUpdateOne) RemoveRelationshipIDs(ids ...int) *CharacterUpdateOne {
	_u.mutation.RemoveRelationshipIDs(ids...)
	return _u
}

// RemoveRelationships removes "relationships" edges to Relationship entities.
func (_u *CharacterUpdateOne) RemoveRelationships(v ...*Relationship) *CharacterUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRelationshipIDs(ids...)
}

// Where appends a list predicates to the CharacterUpdate builder.
func (_u *CharacterUpdateOne) Where(ps ...predicate.Character) *CharacterUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CharacterUpdateOne) Select(field string, fields ...string) *CharacterUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Character entity.
func (_u *CharacterUpdateOne) Save(ctx context.Context) (*Character, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CharacterUpdateOne) SaveX(ctx context.Context) *Character {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CharacterUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CharacterUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CharacterUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := character.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *CharacterUpdateOne) sqlSave(ctx context.Context) (_node *Character, err error) {
	_spec := sqlgraph.NewUpdateSpec(character.Table, character.Columns, sqlgraph.NewFieldSpec(character.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Character.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, character.FieldID)
		for _, f := range fields {
			if !character.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != character.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.NovelID(); ok {
		_spec.SetField(character.FieldNovelID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(character.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Gender(); ok {
		_spec.SetField(character.FieldGender, field.TypeString, value)
	}
	if _u.mutation.GenderCleared() {
		_spec.ClearField(character.FieldGender, field.TypeString)
	}
	if value, ok := _u.mutation.Age(); ok {
		_spec.SetField(character.FieldAge, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAge(); ok {
		_spec.AddField(character.FieldAge, field.TypeInt, value)
	}
	if _u.mutation.AgeCleared() {
		_spec.ClearField(character.FieldAge, field.TypeInt)
	}
	if value, ok := _u.mutation.Appearance(); ok {
		_spec.SetField(character.FieldAppearance, field.TypeString, value)
	}
	if _u.mutation.AppearanceCleared() {
		_spec.ClearField(character.FieldAppearance, field.TypeString)
	}
	if value, ok := _u.mutation.Personality(); ok {
		_spec.SetField(character.FieldPersonality, field.TypeString, value)
	}
	if _u.mutation.PersonalityCleared() {
		_spec.ClearField(character.FieldPersonality, field.TypeString)
	}
	if value, ok := _u.mutation.Background(); ok {
		_spec.SetField(character.FieldBackground, field.TypeString, value)
	}
	if _u.mutation.BackgroundCleared() {
		_spec.ClearField(character.FieldBackground, field.TypeString)
	}
	if value, ok := _u.mutation.CurrentStatus(); ok {
		_spec.SetField(character.FieldCurrentStatus, field.TypeString, value)
	}
	if _u.mutation.CurrentStatusCleared() {
		_spec.ClearField(character.FieldCurrentStatus, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(character.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(character.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.RelationshipsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   character.RelationshipsTable,
			Columns: []string{character.RelationshipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(relationship.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRelationshipsIDs(); len(nodes) > 0 && !_u.mutation.RelationshipsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   character.RelationshipsTable,
			Columns: []string{character.RelationshipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(relationship.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RelationshipsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   character.RelationshipsTable,
			Columns: []string{character.RelationshipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(relationship.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Character{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{character.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
