// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ai-novel/studio/ent/chapter"
	"github.com/ai-novel/studio/ent/character"
	"github.com/ai-novel/studio/ent/characterstateversion"
)

// CharacterStateVersionCreate is the builder for creating a CharacterStateVersion entity.
type CharacterStateVersionCreate struct {
	config
	mutation *CharacterStateVersionMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCharacterID sets the "character_id" field.
func (_c *CharacterStateVersionCreate) SetCharacterID(v int) *CharacterStateVersionCreate {
	_c.mutation.SetCharacterID(v)
	return _c
}

// SetChapterID sets the "chapter_id" field.
func (_c *CharacterStateVersionCreate) SetChapterID(v int) *CharacterStateVersionCreate {
	_c.mutation.SetChapterID(v)
	return _c
}

// SetChapterIndex sets the "chapter_index" field.
func (_c *CharacterStateVersionCreate) SetChapterIndex(v int) *CharacterStateVersionCreate {
	_c.mutation.SetChapterIndex(v)
	return _c
}

// SetGenerationID sets the "generation_id" field.
func (_c *CharacterStateVersionCreate) SetGenerationID(v string) *CharacterStateVersionCreate {
	_c.mutation.SetGenerationID(v)
	return _c
}

// SetCurrentStatus sets the "current_status" field.
func (_c *CharacterStateVersionCreate) SetCurrentStatus(v string) *CharacterStateVersionCreate {
	_c.mutation.SetCurrentStatus(v)
	return _c
}

// SetValid sets the "valid" field.
func (_c *CharacterStateVersionCreate) SetValid(v bool) *CharacterStateVersionCreate {
	_c.mutation.SetValid(v)
	return _c
}

// SetNillableValid sets the "valid" field if the given value is not nil.
func (_c *CharacterStateVersionCreate) SetNillableValid(v *bool) *CharacterStateVersionCreate {
	if v != nil {
		_c.SetValid(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *CharacterStateVersionCreate) SetCreatedAt(v time.Time) *CharacterStateVersionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *CharacterStateVersionCreate) SetNillableCreatedAt(v *time.Time) *CharacterStateVersionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *CharacterStateVersionCreate) SetUpdatedAt(v time.Time) *CharacterStateVersionCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *CharacterStateVersionCreate) SetNillableUpdatedAt(v *time.Time) *CharacterStateVersionCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetChapter sets the "chapter" edge to the Chapter entity.
func (_c *CharacterStateVersionCreate) SetChapter(v *Chapter) *CharacterStateVersionCreate {
	return _c.SetChapterID(v.ID)
}

// SetCharacter sets the "character" edge to the Character entity.
func (_c *CharacterStateVersionCreate) SetCharacter(v *Character) *CharacterStateVersionCreate {
	return _c.SetCharacterID(v.ID)
}

// Mutation returns the CharacterStateVersionMutation object of the builder.
func (_c *CharacterStateVersionCreate) Mutation() *CharacterStateVersionMutation {
	return _c.mutation
}

// Save creates the CharacterStateVersion in the database.
func (_c *CharacterStateVersionCreate) Save(ctx context.Context) (*CharacterStateVersion, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CharacterStateVersionCreate) SaveX(ctx context.Context) *CharacterStateVersion {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CharacterStateVersionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CharacterStateVersionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CharacterStateVersionCreate) defaults() {
	if _, ok := _c.mutation.Valid(); !ok {
		v := characterstateversion.DefaultValid
		_c.mutation.SetValid(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := characterstateversion.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := characterstateversion.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CharacterStateVersionCreate) check() error {
	if _, ok := _c.mutation.CharacterID(); !ok {
		return &ValidationError{Name: "character_id", err: errors.New(`ent: missing required field "CharacterStateVersion.character_id"`)}
	}
	if v, ok := _c.mutation.CharacterID(); ok {
		if err := characterstateversion.CharacterIDValidator(v); err != nil {
			return &ValidationError{Name: "character_id", err: fmt.Errorf(`ent: validator failed for field "CharacterStateVersion.character_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ChapterID(); !ok {
		return &ValidationError{Name: "chapter_id", err: errors.New(`ent: missing required field "CharacterStateVersion.chapter_id"`)}
	}
	if v, ok := _c.mutation.ChapterID(); ok {
		if err := characterstateversion.ChapterIDValidator(v); err != nil {
			return &ValidationError{Name: "chapter_id", err: fmt.Errorf(`ent: validator failed for field "CharacterStateVersion.chapter_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ChapterIndex(); !ok {
		return &ValidationError{Name: "chapter_index", err: errors.New(`ent: missing required field "CharacterStateVersion.chapter_index"`)}
	}
	if v, ok := _c.mutation.ChapterIndex(); ok {
		if err := characterstateversion.ChapterIndexValidator(v); err != nil {
			return &ValidationError{Name: "chapter_index", err: fmt.Errorf(`ent: validator failed for field "CharacterStateVersion.chapter_index": %w`, err)}
		}
	}
	if _, ok := _c.mutation.GenerationID(); !ok {
		return &ValidationError{Name: "generation_id", err: errors.New(`ent: missing required field "CharacterStateVersion.generation_id"`)}
	}
	if _, ok := _c.mutation.CurrentStatus(); !ok {
		return &ValidationError{Name: "current_status", err: errors.New(`ent: missing required field "CharacterStateVersion.current_status"`)}
	}
	if _, ok := _c.mutation.Valid(); !ok {
		return &ValidationError{Name: "valid", err: errors.New(`ent: missing required field "CharacterStateVersion.valid"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "CharacterStateVersion.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "CharacterStateVersion.updated_at"`)}
	}
	if len(_c.mutation.ChapterIDs()) == 0 {
		return &ValidationError{Name: "chapter", err: errors.New(`ent: missing required edge "CharacterStateVersion.chapter"`)}
	}
	if len(_c.mutation.CharacterIDs()) == 0 {
		return &ValidationError{Name: "character", err: errors.New(`ent: missing required edge "CharacterStateVersion.character"`)}
	}
	return nil
}

func (_c *CharacterStateVersionCreate) sqlSave(ctx context.Context) (*CharacterStateVersion, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CharacterStateVersionCreate) createSpec() (*CharacterStateVersion, *sqlgraph.CreateSpec) {
	var (
		_node = &CharacterStateVersion{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(characterstateversion.Table, sqlgraph.NewFieldSpec(characterstateversion.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.ChapterIndex(); ok {
		_spec.SetField(characterstateversion.FieldChapterIndex, field.TypeInt, value)
		_node.ChapterIndex = value
	}
	if value, ok := _c.mutation.GenerationID(); ok {
		_spec.SetField(characterstateversion.FieldGenerationID, field.TypeString, value)
		_node.GenerationID = value
	}
	if value, ok := _c.mutation.CurrentStatus(); ok {
		_spec.SetField(characterstateversion.FieldCurrentStatus, field.TypeString, value)
		_node.CurrentStatus = value
	}
	if value, ok := _c.mutation.Valid(); ok {
		_spec.SetField(characterstateversion.FieldValid, field.TypeBool, value)
		_node.Valid = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(characterstateversion.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(characterstateversion.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.ChapterIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   characterstateversion.ChapterTable,
			Columns: []string{characterstateversion.ChapterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chapter.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ChapterID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.CharacterIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   characterstateversion.CharacterTable,
			Columns: []string{characterstateversion.CharacterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(character.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.CharacterID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CharacterStateVersion.Create().
//		SetCharacterID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CharacterStateVersionUpsert) {
//			SetCharacterID(v+v).
//		}).
//		Exec(ctx)
func (_c *CharacterStateVersionCreate) OnConflict(opts ...sql.ConflictOption) *CharacterStateVersionUpsertOne {
	_c.conflict = opts
	return &CharacterStateVersionUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CharacterStateVersion.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CharacterStateVersionCreate) OnConflictColumns(columns ...string) *CharacterStateVersionUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CharacterStateVersionUpsertOne{
		create: _c,
	}
}

type (
	// CharacterStateVersionUpsertOne is the builder for "upsert"-ing
	//  one CharacterStateVersion node.
	CharacterStateVersionUpsertOne struct {
		create *CharacterStateVersionCreate
	}

	// CharacterStateVersionUpsert is the "OnConflict" setter.
	CharacterStateVersionUpsert struct {
		*sql.UpdateSet
	}
)

// SetCharacterID sets the "character_id" field.
func (u *CharacterStateVersionUpsert) SetCharacterID(v int) *CharacterStateVersionUpsert {
	u.Set(characterstateversion.FieldCharacterID, v)
	return u
}

// UpdateCharacterID sets the "character_id" field to the value that was provided on create.
func (u *CharacterStateVersionUpsert) UpdateCharacterID() *CharacterStateVersionUpsert {
	u.SetExcluded(characterstateversion.FieldCharacterID)
	return u
}

// SetChapterID sets the "chapter_id" field.
func (u *CharacterStateVersionUpsert) SetChapterID(v int) *CharacterStateVersionUpsert {
	u.Set(characterstateversion.FieldChapterID, v)
	return u
}

// UpdateChapterID sets the "chapter_id" field to the value that was provided on create.
func (u *CharacterStateVersionUpsert) UpdateChapterID() *CharacterStateVersionUpsert {
	u.SetExcluded(characterstateversion.FieldChapterID)
	return u
}

// SetChapterIndex sets the "chapter_index" field.
func (u *CharacterStateVersionUpsert) SetChapterIndex(v int) *CharacterStateVersionUpsert {
	u.Set(characterstateversion.FieldChapterIndex, v)
	return u
}

// UpdateChapterIndex sets the "chapter_index" field to the value that was provided on create.
func (u *CharacterStateVersionUpsert) UpdateChapterIndex() *CharacterStateVersionUpsert {
	u.SetExcluded(characterstateversion.FieldChapterIndex)
	return u
}

// AddChapterIndex adds v to the "chapter_index" field.
func (u *CharacterStateVersionUpsert) AddChapterIndex(v int) *CharacterStateVersionUpsert {
	u.Add(characterstateversion.FieldChapterIndex, v)
	return u
}

// SetGenerationID sets the "generation_id" field.
func (u *CharacterStateVersionUpsert) SetGenerationID(v string) *CharacterStateVersionUpsert {
	u.Set(characterstateversion.FieldGenerationID, v)
	return u
}

// UpdateGenerationID sets the "generation_id" field to the value that was provided on create.
func (u *CharacterStateVersionUpsert) UpdateGenerationID() *CharacterStateVersionUpsert {
	u.SetExcluded(characterstateversion.FieldGenerationID)
	return u
}

// SetCurrentStatus sets the "current_status" field.
func (u *CharacterStateVersionUpsert) SetCurrentStatus(v string) *CharacterStateVersionUpsert {
	u.Set(characterstateversion.FieldCurrentStatus, v)
	return u
}

// UpdateCurrentStatus sets the "current_status" field to the value that was provided on create.
func (u *CharacterStateVersionUpsert) UpdateCurrentStatus() *CharacterStateVersionUpsert {
	u.SetExcluded(characterstateversion.FieldCurrentStatus)
	return u
}

// SetValid sets the "valid" field.
func (u *CharacterStateVersionUpsert) SetValid(v bool) *CharacterStateVersionUpsert {
	u.Set(characterstateversion.FieldValid, v)
	return u
}

// UpdateValid sets the "valid" field to the value that was provided on create.
func (u *CharacterStateVersionUpsert) UpdateValid() *CharacterStateVersionUpsert {
	u.SetExcluded(characterstateversion.FieldValid)
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *CharacterStateVersionUpsert) SetCreatedAt(v time.Time) *CharacterStateVersionUpsert {
	u.Set(characterstateversion.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *CharacterStateVersionUpsert) UpdateCreatedAt() *CharacterStateVersionUpsert {
	u.SetExcluded(characterstateversion.FieldCreatedAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CharacterStateVersionUpsert) SetUpdatedAt(v time.Time) *CharacterStateVersionUpsert {
	u.Set(characterstateversion.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CharacterStateVersionUpsert) UpdateUpdatedAt() *CharacterStateVersionUpsert {
	u.SetExcluded(characterstateversion.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.CharacterStateVersion.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CharacterStateVersionUpsertOne) UpdateNewValues() *CharacterStateVersionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CharacterStateVersion.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *CharacterStateVersionUpsertOne) Ignore() *CharacterStateVersionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CharacterStateVersionUpsertOne) DoNothing() *CharacterStateVersionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CharacterStateVersionCreate.OnConflict
// documentation for more info.
func (u *CharacterStateVersionUpsertOne) Update(set func(*CharacterStateVersionUpsert)) *CharacterStateVersionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CharacterStateVersionUpsert{UpdateSet: update})
	}))
	return u
}

// SetCharacterID sets the "character_id" field.
func (u *CharacterStateVersionUpsertOne) SetCharacterID(v int) *CharacterStateVersionUpsertOne {
	return u.Update(func(s *CharacterStateVersionUpsert) {
		s.SetCharacterID(v)
	})
}

// UpdateCharacterID sets the "character_id" field to the value that was provided on create.
func (u *CharacterStateVersionUpsertOne) UpdateCharacterID() *CharacterStateVersionUpsertOne {
	return u.Update(func(s *CharacterStateVersionUpsert) {
		s.UpdateCharacterID()
	})
}

// SetChapterID sets the "chapter_id" field.
func (u *CharacterStateVersionUpsertOne) SetChapterID(v int) *CharacterStateVersionUpsertOne {
	return u.Update(func(s *CharacterStateVersionUpsert) {
		s.SetChapterID(v)
	})
}

// UpdateChapterID sets the "chapter_id" field to the value that was provided on create.
func (u *CharacterStateVersionUpsertOne) UpdateChapterID() *CharacterStateVersionUpsertOne {
	return u.Update(func(s *CharacterStateVersionUpsert) {
		s.UpdateChapterID()
	})
}

// SetChapterIndex sets the "chapter_index" field.
func (u *CharacterStateVersionUpsertOne) SetChapterIndex(v int) *CharacterStateVersionUpsertOne {
	return u.Update(func(s *CharacterStateVersionUpsert) {
		s.SetChapterIndex(v)
	})
}

// AddChapterIndex adds v to the "chapter_index" field.
func (u *CharacterStateVersionUpsertOne) AddChapterIndex(v int) *CharacterStateVersionUpsertOne {
	return u.Update(func(s *CharacterStateVersionUpsert) {
		s.AddChapterIndex(v)
	})
}

// UpdateChapterIndex sets the "chapter_index" field to the value that was provided on create.
func (u *CharacterStateVersionUpsertOne) UpdateChapterIndex() *CharacterStateVersionUpsertOne {
	return u.Update(func(s *CharacterStateVersionUpsert) {
		s.UpdateChapterIndex()
	})
}

// SetGenerationID sets the "generation_id" field.
func (u *CharacterStateVersionUpsertOne) SetGenerationID(v string) *CharacterStateVersionUpsertOne {
	return u.Update(func(s *CharacterStateVersionUpsert) {
		s.SetGenerationID(v)
	})
}

// UpdateGenerationID sets the "generation_id" field to the value that was provided on create.
func (u *CharacterStateVersionUpsertOne) UpdateGenerationID() *CharacterStateVersionUpsertOne {
	return u.Update(func(s *CharacterStateVersionUpsert) {
		s.UpdateGenerationID()
	})
}

// SetCurrentStatus sets the "current_status" field.
func (u *CharacterStateVersionUpsertOne) SetCurrentStatus(v string) *CharacterStateVersionUpsertOne {
	return u.Update(func(s *CharacterStateVersionUpsert) {
		s.SetCurrentStatus(v)
	})
}

// UpdateCurrentStatus sets the "current_status" field to the value that was provided on create.
func (u *CharacterStateVersionUpsertOne) UpdateCurrentStatus() *CharacterStateVersionUpsertOne {
	return u.Update(func(s *CharacterStateVersionUpsert) {
		s.UpdateCurrentStatus()
	})
}

// SetValid sets the "valid" field.
func (u *CharacterStateVersionUpsertOne) SetValid(v bool) *CharacterStateVersionUpsertOne {
	return u.Update(func(s *CharacterStateVersionUpsert) {
		s.SetValid(v)
	})
}

// UpdateValid sets the "valid" field to the value that was provided on create.
func (u *CharacterStateVersionUpsertOne) UpdateValid() *CharacterStateVersionUpsertOne {
	return u.Update(func(s *CharacterStateVersionUpsert) {
		s.UpdateValid()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *CharacterStateVersionUpsertOne) SetCreatedAt(v time.Time) *CharacterStateVersionUpsertOne {
	return u.Update(func(s *CharacterStateVersionUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *CharacterStateVersionUpsertOne) UpdateCreatedAt() *CharacterStateVersionUpsertOne {
	return u.Update(func(s *CharacterStateVersionUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CharacterStateVersionUpsertOne) SetUpdatedAt(v time.Time) *CharacterStateVersionUpsertOne {
	return u.Update(func(s *CharacterStateVersionUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CharacterStateVersionUpsertOne) UpdateUpdatedAt() *CharacterStateVersionUpsertOne {
	return u.Update(func(s *CharacterStateVersionUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *CharacterStateVersionUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CharacterStateVersionCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CharacterStateVersionUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *CharacterStateVersionUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *CharacterStateVersionUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// CharacterStateVersionCreateBulk is the builder for creating many CharacterStateVersion entities in bulk.
type CharacterStateVersionCreateBulk struct {
	config
	err      error
	builders []*CharacterStateVersionCreate
	conflict []sql.ConflictOption
}

// Save creates the CharacterStateVersion entities in the database.
func (_c *CharacterStateVersionCreateBulk) Save(ctx context.Context) ([]*CharacterStateVersion, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*CharacterStateVersion, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CharacterStateVersionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CharacterStateVersionCreateBulk) SaveX(ctx context.Context) []*CharacterStateVersion {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CharacterStateVersionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CharacterStateVersionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CharacterStateVersion.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CharacterStateVersionUpsert) {
//			SetCharacterID(v+v).
//		}).
//		Exec(ctx)
func (_c *CharacterStateVersionCreateBulk) OnConflict(opts ...sql.ConflictOption) *CharacterStateVersionUpsertBulk {
	_c.conflict = opts
	return &CharacterStateVersionUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CharacterStateVersion.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CharacterStateVersionCreateBulk) OnConflictColumns(columns ...string) *CharacterStateVersionUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CharacterStateVersionUpsertBulk{
		create: _c,
	}
}

// CharacterStateVersionUpsertBulk is the builder for "upsert"-ing
// a bulk of CharacterStateVersion nodes.
type CharacterStateVersionUpsertBulk struct {
	create *CharacterStateVersionCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.CharacterStateVersion.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CharacterStateVersionUpsertBulk) UpdateNewValues() *CharacterStateVersionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CharacterStateVersion.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *CharacterStateVersionUpsertBulk) Ignore() *CharacterStateVersionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CharacterStateVersionUpsertBulk) DoNothing() *CharacterStateVersionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CharacterStateVersionCreateBulk.OnConflict
// documentation for more info.
func (u *CharacterStateVersionUpsertBulk) Update(set func(*CharacterStateVersionUpsert)) *CharacterStateVersionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CharacterStateVersionUpsert{UpdateSet: update})
	}))
	return u
}

// SetCharacterID sets the "character_id" field.
func (u *CharacterStateVersionUpsertBulk) SetCharacterID(v int) *CharacterStateVersionUpsertBulk {
	return u.Update(func(s *CharacterStateVersionUpsert) {
		s.SetCharacterID(v)
	})
}

// UpdateCharacterID sets the "character_id" field to the value that was provided on create.
func (u *CharacterStateVersionUpsertBulk) UpdateCharacterID() *CharacterStateVersionUpsertBulk {
	return u.Update(func(s *CharacterStateVersionUpsert) {
		s.UpdateCharacterID()
	})
}

// SetChapterID sets the "chapter_id" field.
func (u *CharacterStateVersionUpsertBulk) SetChapterID(v int) *CharacterStateVersionUpsertBulk {
	return u.Update(func(s *CharacterStateVersionUpsert) {
		s.SetChapterID(v)
	})
}

// UpdateChapterID sets the "chapter_id" field to the value that was provided on create.
func (u *CharacterStateVersionUpsertBulk) UpdateChapterID() *CharacterStateVersionUpsertBulk {
	return u.Update(func(s *CharacterStateVersionUpsert) {
		s.UpdateChapterID()
	})
}

// SetChapterIndex sets the "chapter_index" field.
func (u *CharacterStateVersionUpsertBulk) SetChapterIndex(v int) *CharacterStateVersionUpsertBulk {
	return u.Update(func(s *CharacterStateVersionUpsert) {
		s.SetChapterIndex(v)
	})
}

// AddChapterIndex adds v to the "chapter_index" field.
func (u *CharacterStateVersionUpsertBulk) AddChapterIndex(v int) *CharacterStateVersionUpsertBulk {
	return u.Update(func(s *CharacterStateVersionUpsert) {
		s.AddChapterIndex(v)
	})
}

// UpdateChapterIndex sets the "chapter_index" field to the value that was provided on create.
func (u *CharacterStateVersionUpsertBulk) UpdateChapterIndex() *CharacterStateVersionUpsertBulk {
	return u.Update(func(s *CharacterStateVersionUpsert) {
		s.UpdateChapterIndex()
	})
}

// SetGenerationID sets the "generation_id" field.
func (u *CharacterStateVersionUpsertBulk) SetGenerationID(v string) *CharacterStateVersionUpsertBulk {
	return u.Update(func(s *CharacterStateVersionUpsert) {
		s.SetGenerationID(v)
	})
}

// UpdateGenerationID sets the "generation_id" field to the value that was provided on create.
func (u *CharacterStateVersionUpsertBulk) UpdateGenerationID() *CharacterStateVersionUpsertBulk {
	return u.Update(func(s *CharacterStateVersionUpsert) {
		s.UpdateGenerationID()
	})
}

// SetCurrentStatus sets the "current_status" field.
func (u *CharacterStateVersionUpsertBulk) SetCurrentStatus(v string) *CharacterStateVersionUpsertBulk {
	return u.Update(func(s *CharacterStateVersionUpsert) {
		s.SetCurrentStatus(v)
	})
}

// UpdateCurrentStatus sets the "current_status" field to the value that was provided on create.
func (u *CharacterStateVersionUpsertBulk) UpdateCurrentStatus() *CharacterStateVersionUpsertBulk {
	return u.Update(func(s *CharacterStateVersionUpsert) {
		s.UpdateCurrentStatus()
	})
}

// SetValid sets the "valid" field.
func (u *CharacterStateVersionUpsertBulk) SetValid(v bool) *CharacterStateVersionUpsertBulk {
	return u.Update(func(s *CharacterStateVersionUpsert) {
		s.SetValid(v)
	})
}

// UpdateValid sets the "valid" field to the value that was provided on create.
func (u *CharacterStateVersionUpsertBulk) UpdateValid() *CharacterStateVersionUpsertBulk {
	return u.Update(func(s *CharacterStateVersionUpsert) {
		s.UpdateValid()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *CharacterStateVersionUpsertBulk) SetCreatedAt(v time.Time) *CharacterStateVersionUpsertBulk {
	return u.Update(func(s *CharacterStateVersionUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *CharacterStateVersionUpsertBulk) UpdateCreatedAt() *CharacterStateVersionUpsertBulk {
	return u.Update(func(s *CharacterStateVersionUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CharacterStateVersionUpsertBulk) SetUpdatedAt(v time.Time) *CharacterStateVersionUpsertBulk {
	return u.Update(func(s *CharacterStateVersionUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CharacterStateVersionUpsertBulk) UpdateUpdatedAt() *CharacterStateVersionUpsertBulk {
	return u.Update(func(s *CharacterStateVersionUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *CharacterStateVersionUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the CharacterStateVersionCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CharacterStateVersionCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CharacterStateVersionUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
