// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/ai-novel/studio/ent/chapter"
	"github.com/ai-novel/studio/ent/character"
	"github.com/ai-novel/studio/ent/relationshipstateversion"
)

// RelationshipStateVersion is the model entity for the RelationshipStateVersion schema.
type RelationshipStateVersion struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// ChapterID holds the value of the "chapter_id" field.
	ChapterID int `json:"chapter_id,omitempty"`
	// SourceCharacterID holds the value of the "source_character_id" field.
	SourceCharacterID int `json:"source_character_id,omitempty"`
	// TargetCharacterID holds the value of the "target_character_id" field.
	TargetCharacterID int `json:"target_character_id,omitempty"`
	// ChapterIndex holds the value of the "chapter_index" field.
	ChapterIndex int `json:"chapter_index,omitempty"`
	// GenerationID holds the value of the "generation_id" field.
	GenerationID string `json:"generation_id,omitempty"`
	// RelationType holds the value of the "relation_type" field.
	RelationType string `json:"relation_type,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// Active holds the value of the "active" field.
	Active bool `json:"active,omitempty"`
	// Valid holds the value of the "valid" field.
	Valid bool `json:"valid,omitempty"`
	// Operation holds the value of the "operation" field.
	Operation relationshipstateversion.Operation `json:"operation,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the RelationshipStateVersionQuery when eager-loading is set.
	Edges        RelationshipStateVersionEdges `json:"edges"`
	selectValues sql.SelectValues
}

// RelationshipStateVersionEdges holds the relations/edges for other nodes in the graph.
type RelationshipStateVersionEdges struct {
	// Chapter holds the value of the chapter edge.
	Chapter *Chapter `json:"chapter,omitempty"`
	// SourceCharacter holds the value of the source_character edge.
	SourceCharacter *Character `json:"source_character,omitempty"`
	// TargetCharacter holds the value of the target_character edge.
	TargetCharacter *Character `json:"target_character,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// ChapterOrErr returns the Chapter value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RelationshipStateVersionEdges) ChapterOrErr() (*Chapter, error) {
	if e.Chapter != nil {
		return e.Chapter, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: chapter.Label}
	}
	return nil, &NotLoadedError{edge: "chapter"}
}

// SourceCharacterOrErr returns the SourceCharacter value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RelationshipStateVersionEdges) SourceCharacterOrErr() (*Character, error) {
	if e.SourceCharacter != nil {
		return e.SourceCharacter, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: character.Label}
	}
	return nil, &NotLoadedError{edge: "source_character"}
}

// TargetCharacterOrErr returns the TargetCharacter value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RelationshipStateVersionEdges) TargetCharacterOrErr() (*Character, error) {
	if e.TargetCharacter != nil {
		return e.TargetCharacter, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: character.Label}
	}
	return nil, &NotLoadedError{edge: "target_character"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*RelationshipStateVersion) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case relationshipstateversion.FieldActive, relationshipstateversion.FieldValid:
			values[i] = new(sql.NullBool)
		case relationshipstateversion.FieldID, relationshipstateversion.FieldChapterID, relationshipstateversion.FieldSourceCharacterID, relationshipstateversion.FieldTargetCharacterID, relationshipstateversion.FieldChapterIndex:
			values[i] = new(sql.NullInt64)
		case relationshipstateversion.FieldGenerationID, relationshipstateversion.FieldRelationType, relationshipstateversion.FieldDescription, relationshipstateversion.FieldOperation:
			values[i] = new(sql.NullString)
		case relationshipstateversion.FieldCreatedAt, relationshipstateversion.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the RelationshipStateVersion fields.
func (_m *RelationshipStateVersion) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case relationshipstateversion.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case relationshipstateversion.FieldChapterID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field chapter_id", values[i])
			} else if value.Valid {
				_m.ChapterID = int(value.Int64)
			}
		case relationshipstateversion.FieldSourceCharacterID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field source_character_id", values[i])
			} else if value.Valid {
				_m.SourceCharacterID = int(value.Int64)
			}
		case relationshipstateversion.FieldTargetCharacterID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field target_character_id", values[i])
			} else if value.Valid {
				_m.TargetCharacterID = int(value.Int64)
			}
		case relationshipstateversion.FieldChapterIndex:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field chapter_index", values[i])
			} else if value.Valid {
				_m.ChapterIndex = int(value.Int64)
			}
		case relationshipstateversion.FieldGenerationID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field generation_id", values[i])
			} else if value.Valid {
				_m.GenerationID = value.String
			}
		case relationshipstateversion.FieldRelationType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field relation_type", values[i])
			} else if value.Valid {
				_m.RelationType = value.String
			}
		case relationshipstateversion.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case relationshipstateversion.FieldActive:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field active", values[i])
			} else if value.Valid {
				_m.Active = value.Bool
			}
		case relationshipstateversion.FieldValid:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field valid", values[i])
			} else if value.Valid {
				_m.Valid = value.Bool
			}
		case relationshipstateversion.FieldOperation:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field operation", values[i])
			} else if value.Valid {
				_m.Operation = relationshipstateversion.Operation(value.String)
			}
		case relationshipstateversion.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case relationshipstateversion.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the RelationshipStateVersion.
// This includes values selected through modifiers, order, etc.
func (_m *RelationshipStateVersion) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryChapter queries the "chapter" edge of the RelationshipStateVersion entity.
func (_m *RelationshipStateVersion) QueryChapter() *ChapterQuery {
	return NewRelationshipStateVersionClient(_m.config).QueryChapter(_m)
}

// QuerySourceCharacter queries the "source_character" edge of the RelationshipStateVersion entity.
func (_m *RelationshipStateVersion) QuerySourceCharacter() *CharacterQuery {
	return NewRelationshipStateVersionClient(_m.config).QuerySourceCharacter(_m)
}

// QueryTargetCharacter queries the "target_character" edge of the RelationshipStateVersion entity.
func (_m *RelationshipStateVersion) QueryTargetCharacter() *CharacterQuery {
	return NewRelationshipStateVersionClient(_m.config).QueryTargetCharacter(_m)
}

// Update returns a builder for updating this RelationshipStateVersion.
// Note that you need to call RelationshipStateVersion.Unwrap() before calling this method if this RelationshipStateVersion
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *RelationshipStateVersion) Update() *RelationshipStateVersionUpdateOne {
	return NewRelationshipStateVersionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the RelationshipStateVersion entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *RelationshipStateVersion) Unwrap() *RelationshipStateVersion {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: RelationshipStateVersion is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *RelationshipStateVersion) String() string {
	var builder strings.Builder
	builder.WriteString("RelationshipStateVersion(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("chapter_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ChapterID))
	builder.WriteString(", ")
	builder.WriteString("source_character_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.SourceCharacterID))
	builder.WriteString(", ")
	builder.WriteString("target_character_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TargetCharacterID))
	builder.WriteString(", ")
	builder.WriteString("chapter_index=")
	builder.WriteString(fmt.Sprintf("%v", _m.ChapterIndex))
	builder.WriteString(", ")
	builder.WriteString("generation_id=")
	builder.WriteString(_m.GenerationID)
	builder.WriteString(", ")
	builder.WriteString("relation_type=")
	builder.WriteString(_m.RelationType)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("active=")
	builder.WriteString(fmt.Sprintf("%v", _m.Active))
	builder.WriteString(", ")
	builder.WriteString("valid=")
	builder.WriteString(fmt.Sprintf("%v", _m.Valid))
	builder.WriteString(", ")
	builder.WriteString("operation=")
	builder.WriteString(fmt.Sprintf("%v", _m.Operation))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// RelationshipStateVersions is a parsable slice of RelationshipStateVersion.
type RelationshipStateVersions []*RelationshipStateVersion
