// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/ai-novel/studio/ent/character"
	"github.com/ai-novel/studio/ent/relationship"
)

// Relationship is the model entity for the Relationship schema.
type Relationship struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// NovelID holds the value of the "novel_id" field.
	NovelID string `json:"novel_id,omitempty"`
	// RelationType holds the value of the "relation_type" field.
	RelationType string `json:"relation_type,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the RelationshipQuery when eager-loading is set.
	Edges                         RelationshipEdges `json:"edges"`
	character_relationships       *int
	relationship_target_character *int
	selectValues                  sql.SelectValues
}

// RelationshipEdges holds the relations/edges for other nodes in the graph.
type RelationshipEdges struct {
	// Character holds the value of the character edge.
	Character *Character `json:"character,omitempty"`
	// TargetCharacter holds the value of the target_character edge.
	TargetCharacter *Character `json:"target_character,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// CharacterOrErr returns the Character value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RelationshipEdges) CharacterOrErr() (*Character, error) {
	if e.Character != nil {
		return e.Character, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: character.Label}
	}
	return nil, &NotLoadedError{edge: "character"}
}

// TargetCharacterOrErr returns the TargetCharacter value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RelationshipEdges) TargetCharacterOrErr() (*Character, error) {
	if e.TargetCharacter != nil {
		return e.TargetCharacter, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: character.Label}
	}
	return nil, &NotLoadedError{edge: "target_character"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Relationship) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case relationship.FieldID:
			values[i] = new(sql.NullInt64)
		case relationship.FieldNovelID, relationship.FieldRelationType, relationship.FieldDescription:
			values[i] = new(sql.NullString)
		case relationship.FieldCreatedAt, relationship.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case relationship.ForeignKeys[0]: // character_relationships
			values[i] = new(sql.NullInt64)
		case relationship.ForeignKeys[1]: // relationship_target_character
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Relationship fields.
func (_m *Relationship) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case relationship.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case relationship.FieldNovelID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field novel_id", values[i])
			} else if value.Valid {
				_m.NovelID = value.String
			}
		case relationship.FieldRelationType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field relation_type", values[i])
			} else if value.Valid {
				_m.RelationType = value.String
			}
		case relationship.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case relationship.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case relationship.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case relationship.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field character_relationships", value)
			} else if value.Valid {
				_m.character_relationships = new(int)
				*_m.character_relationships = int(value.Int64)
			}
		case relationship.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field relationship_target_character", value)
			} else if value.Valid {
				_m.relationship_target_character = new(int)
				*_m.relationship_target_character = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Relationship.
// This includes values selected through modifiers, order, etc.
func (_m *Relationship) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryCharacter queries the "character" edge of the Relationship entity.
func (_m *Relationship) QueryCharacter() *CharacterQuery {
	return NewRelationshipClient(_m.config).QueryCharacter(_m)
}

// QueryTargetCharacter queries the "target_character" edge of the Relationship entity.
func (_m *Relationship) QueryTargetCharacter() *CharacterQuery {
	return NewRelationshipClient(_m.config).QueryTargetCharacter(_m)
}

// Update returns a builder for updating this Relationship.
// Note that you need to call Relationship.Unwrap() before calling this method if this Relationship
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Relationship) Update() *RelationshipUpdateOne {
	return NewRelationshipClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Relationship entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Relationship) Unwrap() *Relationship {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Relationship is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Relationship) String() string {
	var builder strings.Builder
	builder.WriteString("Relationship(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("novel_id=")
	builder.WriteString(_m.NovelID)
	builder.WriteString(", ")
	builder.WriteString("relation_type=")
	builder.WriteString(_m.RelationType)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Relationships is a parsable slice of Relationship.
type Relationships []*Relationship
