// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ai-novel/studio/ent/character"
	"github.com/ai-novel/studio/ent/predicate"
	"github.com/ai-novel/studio/ent/relationship"
)

// RelationshipUpdate is the builder for updating Relationship entities.
type RelationshipUpdate struct {
	config
	hooks    []Hook
	mutation *RelationshipMutation
}

// Where appends a list predicates to the RelationshipUpdate builder.
func (_u *RelationshipUpdate) Where(ps ...predicate.Relationship) *RelationshipUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetNovelID sets the "novel_id" field.
func (_u *RelationshipUpdate) SetNovelID(v string) *RelationshipUpdate {
	_u.mutation.SetNovelID(v)
	return _u
}

// SetNillableNovelID sets the "novel_id" field if the given value is not nil.
func (_u *RelationshipUpdate) SetNillableNovelID(v *string) *RelationshipUpdate {
	if v != nil {
		_u.SetNovelID(*v)
	}
	return _u
}

// SetRelationType sets the "relation_type" field.
func (_u *RelationshipUpdate) SetRelationType(v string) *RelationshipUpdate {
	_u.mutation.SetRelationType(v)
	return _u
}

// SetNillableRelationType sets the "relation_type" field if the given value is not nil.
func (_u *RelationshipUpdate) SetNillableRelationType(v *string) *RelationshipUpdate {
	if v != nil {
		_u.SetRelationType(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *RelationshipUpdate) SetDescription(v string) *RelationshipUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *RelationshipUpdate) SetNillableDescription(v *string) *RelationshipUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *RelationshipUpdate) ClearDescription() *RelationshipUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *RelationshipUpdate) SetCreatedAt(v time.Time) *RelationshipUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *RelationshipUpdate) SetNillableCreatedAt(v *time.Time) *RelationshipUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RelationshipUpdate) SetUpdatedAt(v time.Time) *RelationshipUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetCharacterID sets the "character" edge to the Character entity by ID.
func (_u *RelationshipUpdate) SetCharacterID(id int) *RelationshipUpdate {
	_u.mutation.SetCharacterID(id)
	return _u
}

// SetCharacter sets the "character" edge to the Character entity.
func (_u *RelationshipUpdate) SetCharacter(v *Character) *RelationshipUpdate {
	return _u.SetCharacterID(v.ID)
}

// SetTargetCharacterID sets the "target_character" edge to the Character entity by ID.
func (_u *RelationshipUpdate) SetTargetCharacterID(id int) *RelationshipUpdate {
	_u.mutation.SetTargetCharacterID(id)
	return _u
}

// SetTargetCharacter sets the "target_character" edge to the Character entity.
func (_u *RelationshipUpdate) SetTargetCharacter(v *Character) *RelationshipUpdate {
	return _u.SetTargetCharacterID(v.ID)
}

// Mutation returns the RelationshipMutation object of the builder.
func (_u *RelationshipUpdate) Mutation() *RelationshipMutation {
	return _u.mutation
}

// ClearCharacter clears the "character" edge to the Character entity.
func (_u *RelationshipUpdate) ClearCharacter() *RelationshipUpdate {
	_u.mutation.ClearCharacter()
	return _u
}

// ClearTargetCharacter clears the "target_character" edge to the Character entity.
func (_u *RelationshipUpdate) ClearTargetCharacter() *RelationshipUpdate {
	_u.mutation.ClearTargetCharacter()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RelationshipUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RelationshipUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RelationshipUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RelationshipUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RelationshipUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := relationship.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RelationshipUpdate) check() error {
	if _u.mutation.CharacterCleared() && len(_u.mutation.CharacterIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Relationship.character"`)
	}
	if _u.mutation.TargetCharacterCleared() && len(_u.mutation.TargetCharacterIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Relationship.target_character"`)
	}
	return nil
}

func (_u *RelationshipUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(relationship.Table, relationship.Columns, sqlgraph.NewFieldSpec(relationship.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.NovelID(); ok {
		_spec.SetField(relationship.FieldNovelID, field.TypeString, value)
	}
	if value, ok := _u.mutation.RelationType(); ok {
		_spec.SetField(relationship.FieldRelationType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(relationship.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(relationship.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(relationship.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(relationship.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.CharacterCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   relationship.CharacterTable,
			Columns: []string{relationship.CharacterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(character.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CharacterIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   relationship.CharacterTable,
			Columns: []string{relationship.CharacterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(character.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TargetCharacterCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   relationship.TargetCharacterTable,
			Columns: []string{relationship.TargetCharacterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(character.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TargetCharacterIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   relationship.TargetCharacterTable,
			Columns: []string{relationship.TargetCharacterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(character.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{relationship.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RelationshipUpdateOne is the builder for updating a single Relationship entity.
type RelationshipUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RelationshipMutation
}

// SetNovelID sets the "novel_id" field.
func (_u *RelationshipUpdateOne) SetNovelID(v string) *RelationshipUpdateOne {
	_u.mutation.SetNovelID(v)
	return _u
}

// SetNillableNovelID sets the "novel_id" field if the given value is not nil.
func (_u *RelationshipUpdateOne) SetNillableNovelID(v *string) *RelationshipUpdateOne {
	if v != nil {
		_u.SetNovelID(*v)
	}
	return _u
}

// SetRelationType sets the "relation_type" field.
func (_u *RelationshipUpdateOne) SetRelationType(v string) *RelationshipUpdateOne {
	_u.mutation.SetRelationType(v)
	return _u
}

// SetNillableRelationType sets the "relation_type" field if the given value is not nil.
func (_u *RelationshipUpdateOne) SetNillableRelationType(v *string) *RelationshipUpdateOne {
	if v != nil {
		_u.SetRelationType(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *RelationshipUpdateOne) SetDescription(v string) *RelationshipUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *RelationshipUpdateOne) SetNillableDescription(v *string) *RelationshipUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *RelationshipUpdateOne) ClearDescription() *RelationshipUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *RelationshipUpdateOne) SetCreatedAt(v time.Time) *RelationshipUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *RelationshipUpdateOne) SetNillableCreatedAt(v *time.Time) *RelationshipUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RelationshipUpdateOne) SetUpdatedAt(v time.Time) *RelationshipUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetCharacterID sets the "character" edge to the Character entity by ID.
func (_u *RelationshipUpdateOne) SetCharacterID(id int) *RelationshipUpdateOne {
	_u.mutation.SetCharacterID(id)
	return _u
}

// SetCharacter sets the "character" edge to the Character entity.
func (_u *RelationshipUpdateOne) SetCharacter(v *Character) *RelationshipUpdateOne {
	return _u.SetCharacterID(v.ID)
}

// SetTargetCharacterID sets the "target_character" edge to the Character entity by ID.
func (_u *RelationshipUpdateOne) SetTargetCharacterID(id int) *RelationshipUpdateOne {
	_u.mutation.SetTargetCharacterID(id)
	return _u
}

// SetTargetCharacter sets the "target_character" edge to the Character entity.
func (_u *RelationshipUpdateOne) SetTargetCharacter(v *Character) *RelationshipUpdateOne {
	return _u.SetTargetCharacterID(v.ID)
}

// Mutation returns the RelationshipMutation object of the builder.
func (_u *RelationshipUpdateOne) Mutation() *RelationshipMutation {
	return _u.mutation
}

// ClearCharacter clears the "character" edge to the Character entity.
func (_u *RelationshipUpdateOne) ClearCharacter() *RelationshipUpdateOne {
	_u.mutation.ClearCharacter()
	return _u
}

// ClearTargetCharacter clears the "target_character" edge to the Character entity.
func (_u *RelationshipUpdateOne) ClearTargetCharacter() *RelationshipUpdateOne {
	_u.mutation.ClearTargetCharacter()
	return _u
}

// Where appends a list predicates to the RelationshipUpdate builder.
func (_u *RelationshipUpdateOne) Where(ps ...predicate.Relationship) *RelationshipUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RelationshipUpdateOne) Select(field string, fields ...string) *RelationshipUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Relationship entity.
func (_u *RelationshipUpdateOne) Save(ctx context.Context) (*Relationship, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RelationshipUpdateOne) SaveX(ctx context.Context) *Relationship {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RelationshipUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RelationshipUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RelationshipUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := relationship.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RelationshipUpdateOne) check() error {
	if _u.mutation.CharacterCleared() && len(_u.mutation.CharacterIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Relationship.character"`)
	}
	if _u.mutation.TargetCharacterCleared() && len(_u.mutation.TargetCharacterIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Relationship.target_character"`)
	}
	return nil
}

func (_u *RelationshipUpdateOne) sqlSave(ctx context.Context) (_node *Relationship, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(relationship.Table, relationship.Columns, sqlgraph.NewFieldSpec(relationship.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Relationship.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, relationship.FieldID)
		for _, f := range fields {
			if !relationship.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != relationship.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.NovelID(); ok {
		_spec.SetField(relationship.FieldNovelID, field.TypeString, value)
	}
	if value, ok := _u.mutation.RelationType(); ok {
		_spec.SetField(relationship.FieldRelationType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(relationship.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(relationship.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(relationship.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(relationship.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.CharacterCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   relationship.CharacterTable,
			Columns: []string{relationship.CharacterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(character.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CharacterIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   relationship.CharacterTable,
			Columns: []string{relationship.CharacterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(character.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TargetCharacterCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   relationship.TargetCharacterTable,
			Columns: []string{relationship.TargetCharacterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(character.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TargetCharacterIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   relationship.TargetCharacterTable,
			Columns: []string{relationship.TargetCharacterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(character.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Relationship{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{relationship.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
