// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ai-novel/studio/ent/chapter"
	"github.com/ai-novel/studio/ent/character"
	"github.com/ai-novel/studio/ent/predicate"
	"github.com/ai-novel/studio/ent/relationshipstateversion"
)

// RelationshipStateVersionQuery is the builder for querying RelationshipStateVersion entities.
type RelationshipStateVersionQuery struct {
	config
	ctx                 *QueryContext
	order               []relationshipstateversion.OrderOption
	inters              []Interceptor
	predicates          []predicate.RelationshipStateVersion
	withChapter         *ChapterQuery
	withSourceCharacter *CharacterQuery
	withTargetCharacter *CharacterQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the RelationshipStateVersionQuery builder.
func (_q *RelationshipStateVersionQuery) Where(ps ...predicate.RelationshipStateVersion) *RelationshipStateVersionQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *RelationshipStateVersionQuery) Limit(limit int) *RelationshipStateVersionQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *RelationshipStateVersionQuery) Offset(offset int) *RelationshipStateVersionQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *RelationshipStateVersionQuery) Unique(unique bool) *RelationshipStateVersionQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *RelationshipStateVersionQuery) Order(o ...relationshipstateversion.OrderOption) *RelationshipStateVersionQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryChapter chains the current query on the "chapter" edge.
func (_q *RelationshipStateVersionQuery) QueryChapter() *ChapterQuery {
	query := (&ChapterClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(relationshipstateversion.Table, relationshipstateversion.FieldID, selector),
			sqlgraph.To(chapter.Table, chapter.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, relationshipstateversion.ChapterTable, relationshipstateversion.ChapterColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QuerySourceCharacter chains the current query on the "source_character" edge.
func (_q *RelationshipStateVersionQuery) QuerySourceCharacter() *CharacterQuery {
	query := (&CharacterClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(relationshipstateversion.Table, relationshipstateversion.FieldID, selector),
			sqlgraph.To(character.Table, character.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, relationshipstateversion.SourceCharacterTable, relationshipstateversion.SourceCharacterColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryTargetCharacter chains the current query on the "target_character" edge.
func (_q *RelationshipStateVersionQuery) QueryTargetCharacter() *CharacterQuery {
	query := (&CharacterClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(relationshipstateversion.Table, relationshipstateversion.FieldID, selector),
			sqlgraph.To(character.Table, character.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, relationshipstateversion.TargetCharacterTable, relationshipstateversion.TargetCharacterColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first RelationshipStateVersion entity from the query.
// Returns a *NotFoundError when no RelationshipStateVersion was found.
func (_q *RelationshipStateVersionQuery) First(ctx context.Context) (*RelationshipStateVersion, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{relationshipstateversion.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *RelationshipStateVersionQuery) FirstX(ctx context.Context) *RelationshipStateVersion {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first RelationshipStateVersion ID from the query.
// Returns a *NotFoundError when no RelationshipStateVersion ID was found.
func (_q *RelationshipStateVersionQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{relationshipstateversion.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *RelationshipStateVersionQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single RelationshipStateVersion entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one RelationshipStateVersion entity is found.
// Returns a *NotFoundError when no RelationshipStateVersion entities are found.
func (_q *RelationshipStateVersionQuery) Only(ctx context.Context) (*RelationshipStateVersion, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{relationshipstateversion.Label}
	default:
		return nil, &NotSingularError{relationshipstateversion.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *RelationshipStateVersionQuery) OnlyX(ctx context.Context) *RelationshipStateVersion {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only RelationshipStateVersion ID in the query.
// Returns a *NotSingularError when more than one RelationshipStateVersion ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *RelationshipStateVersionQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{relationshipstateversion.Label}
	default:
		err = &NotSingularError{relationshipstateversion.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *RelationshipStateVersionQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of RelationshipStateVersions.
func (_q *RelationshipStateVersionQuery) All(ctx context.Context) ([]*RelationshipStateVersion, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*RelationshipStateVersion, *RelationshipStateVersionQuery]()
	return withInterceptors[[]*RelationshipStateVersion](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *RelationshipStateVersionQuery) AllX(ctx context.Context) []*RelationshipStateVersion {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of RelationshipStateVersion IDs.
func (_q *RelationshipStateVersionQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(relationshipstateversion.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *RelationshipStateVersionQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *RelationshipStateVersionQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*RelationshipStateVersionQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *RelationshipStateVersionQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *RelationshipStateVersionQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *RelationshipStateVersionQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the RelationshipStateVersionQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *RelationshipStateVersionQuery) Clone() *RelationshipStateVersionQuery {
	if _q == nil {
		return nil
	}
	return &RelationshipStateVersionQuery{
		config:              _q.config,
		ctx:                 _q.ctx.Clone(),
		order:               append([]relationshipstateversion.OrderOption{}, _q.order...),
		inters:              append([]Interceptor{}, _q.inters...),
		predicates:          append([]predicate.RelationshipStateVersion{}, _q.predicates...),
		withChapter:         _q.withChapter.Clone(),
		withSourceCharacter: _q.withSourceCharacter.Clone(),
		withTargetCharacter: _q.withTargetCharacter.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithChapter tells the query-builder to eager-load the nodes that are connected to
// the "chapter" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *RelationshipStateVersionQuery) WithChapter(opts ...func(*ChapterQuery)) *RelationshipStateVersionQuery {
	query := (&ChapterClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withChapter = query
	return _q
}

// WithSourceCharacter tells the query-builder to eager-load the nodes that are connected to
// the "source_character" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *RelationshipStateVersionQuery) WithSourceCharacter(opts ...func(*CharacterQuery)) *RelationshipStateVersionQuery {
	query := (&CharacterClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withSourceCharacter = query
	return _q
}

// WithTargetCharacter tells the query-builder to eager-load the nodes that are connected to
// the "target_character" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *RelationshipStateVersionQuery) WithTargetCharacter(opts ...func(*CharacterQuery)) *RelationshipStateVersionQuery {
	query := (&CharacterClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withTargetCharacter = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		ChapterID int `json:"chapter_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.RelationshipStateVersion.Query().
//		GroupBy(relationshipstateversion.FieldChapterID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *RelationshipStateVersionQuery) GroupBy(field string, fields ...string) *RelationshipStateVersionGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &RelationshipStateVersionGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = relationshipstateversion.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		ChapterID int `json:"chapter_id,omitempty"`
//	}
//
//	client.RelationshipStateVersion.Query().
//		Select(relationshipstateversion.FieldChapterID).
//		Scan(ctx, &v)
func (_q *RelationshipStateVersionQuery) Select(fields ...string) *RelationshipStateVersionSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &RelationshipStateVersionSelect{RelationshipStateVersionQuery: _q}
	sbuild.label = relationshipstateversion.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a RelationshipStateVersionSelect configured with the given aggregations.
func (_q *RelationshipStateVersionQuery) Aggregate(fns ...AggregateFunc) *RelationshipStateVersionSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *RelationshipStateVersionQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !relationshipstateversion.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *RelationshipStateVersionQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*RelationshipStateVersion, error) {
	var (
		nodes       = []*RelationshipStateVersion{}
		_spec       = _q.querySpec()
		loadedTypes = [3]bool{
			_q.withChapter != nil,
			_q.withSourceCharacter != nil,
			_q.withTargetCharacter != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*RelationshipStateVersion).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &RelationshipStateVersion{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withChapter; query != nil {
		if err := _q.loadChapter(ctx, query, nodes, nil,
			func(n *RelationshipStateVersion, e *Chapter) { n.Edges.Chapter = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withSourceCharacter; query != nil {
		if err := _q.loadSourceCharacter(ctx, query, nodes, nil,
			func(n *RelationshipStateVersion, e *Character) { n.Edges.SourceCharacter = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withTargetCharacter; query != nil {
		if err := _q.loadTargetCharacter(ctx, query, nodes, nil,
			func(n *RelationshipStateVersion, e *Character) { n.Edges.TargetCharacter = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *RelationshipStateVersionQuery) loadChapter(ctx context.Context, query *ChapterQuery, nodes []*RelationshipStateVersion, init func(*RelationshipStateVersion), assign func(*RelationshipStateVersion, *Chapter)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*RelationshipStateVersion)
	for i := range nodes {
		fk := nodes[i].ChapterID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(chapter.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "chapter_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *RelationshipStateVersionQuery) loadSourceCharacter(ctx context.Context, query *CharacterQuery, nodes []*RelationshipStateVersion, init func(*RelationshipStateVersion), assign func(*RelationshipStateVersion, *Character)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*RelationshipStateVersion)
	for i := range nodes {
		fk := nodes[i].SourceCharacterID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(character.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "source_character_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *RelationshipStateVersionQuery) loadTargetCharacter(ctx context.Context, query *CharacterQuery, nodes []*RelationshipStateVersion, init func(*RelationshipStateVersion), assign func(*RelationshipStateVersion, *Character)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*RelationshipStateVersion)
	for i := range nodes {
		fk := nodes[i].TargetCharacterID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(character.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "target_character_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *RelationshipStateVersionQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *RelationshipStateVersionQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(relationshipstateversion.Table, relationshipstateversion.Columns, sqlgraph.NewFieldSpec(relationshipstateversion.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, relationshipstateversion.FieldID)
		for i := range fields {
			if fields[i] != relationshipstateversion.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withChapter != nil {
			_spec.Node.AddColumnOnce(relationshipstateversion.FieldChapterID)
		}
		if _q.withSourceCharacter != nil {
			_spec.Node.AddColumnOnce(relationshipstateversion.FieldSourceCharacterID)
		}
		if _q.withTargetCharacter != nil {
			_spec.Node.AddColumnOnce(relationshipstateversion.FieldTargetCharacterID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *RelationshipStateVersionQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(relationshipstateversion.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = relationshipstateversion.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// RelationshipStateVersionGroupBy is the group-by builder for RelationshipStateVersion entities.
type RelationshipStateVersionGroupBy struct {
	selector
	build *RelationshipStateVersionQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *RelationshipStateVersionGroupBy) Aggregate(fns ...AggregateFunc) *RelationshipStateVersionGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *RelationshipStateVersionGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*RelationshipStateVersionQuery, *RelationshipStateVersionGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *RelationshipStateVersionGroupBy) sqlScan(ctx context.Context, root *RelationshipStateVersionQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// RelationshipStateVersionSelect is the builder for selecting fields of RelationshipStateVersion entities.
type RelationshipStateVersionSelect struct {
	*RelationshipStateVersionQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *RelationshipStateVersionSelect) Aggregate(fns ...AggregateFunc) *RelationshipStateVersionSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *RelationshipStateVersionSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*RelationshipStateVersionQuery, *RelationshipStateVersionSelect](ctx, _s.RelationshipStateVersionQuery, _s, _s.inters, v)
}

func (_s *RelationshipStateVersionSelect) sqlScan(ctx context.Context, root *RelationshipStateVersionQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
