// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/ai-novel/studio/ent/chapter"
	"github.com/ai-novel/studio/ent/chapterderivedtask"
	"github.com/ai-novel/studio/ent/character"
	"github.com/ai-novel/studio/ent/characterstateversion"
	"github.com/ai-novel/studio/ent/memoryentry"
	"github.com/ai-novel/studio/ent/novel"
	"github.com/ai-novel/studio/ent/relationship"
	"github.com/ai-novel/studio/ent/relationshipstateversion"
	"github.com/ai-novel/studio/ent/schema"
	"github.com/ai-novel/studio/ent/worldsetting"
	"github.com/ai-novel/studio/ent/worldstateversion"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	chapterFields := schema.Chapter{}.Fields()
	_ = chapterFields
	// chapterDescStatus is the schema descriptor for status field.
	chapterDescStatus := chapterFields[4].Descriptor()
	// chapter.DefaultStatus holds the default value on creation for the status field.
	chapter.DefaultStatus = chapterDescStatus.Default.(string)
	// chapterDescDerivedStatus is the schema descriptor for derived_status field.
	chapterDescDerivedStatus := chapterFields[5].Descriptor()
	// chapter.DefaultDerivedStatus holds the default value on creation for the derived_status field.
	chapter.DefaultDerivedStatus = chapterDescDerivedStatus.Default.(string)
	// chapterDescDerivedGenerationID is the schema descriptor for derived_generation_id field.
	chapterDescDerivedGenerationID := chapterFields[6].Descriptor()
	// chapter.DefaultDerivedGenerationID holds the default value on creation for the derived_generation_id field.
	chapter.DefaultDerivedGenerationID = chapterDescDerivedGenerationID.Default.(string)
	// chapterDescLastBeat is the schema descriptor for last_beat field.
	chapterDescLastBeat := chapterFields[7].Descriptor()
	// chapter.DefaultLastBeat holds the default value on creation for the last_beat field.
	chapter.DefaultLastBeat = chapterDescLastBeat.Default.(string)
	// chapterDescNextAction is the schema descriptor for next_action field.
	chapterDescNextAction := chapterFields[9].Descriptor()
	// chapter.DefaultNextAction holds the default value on creation for the next_action field.
	chapter.DefaultNextAction = chapterDescNextAction.Default.(string)
	// chapterDescCreatedAt is the schema descriptor for created_at field.
	chapterDescCreatedAt := chapterFields[10].Descriptor()
	// chapter.DefaultCreatedAt holds the default value on creation for the created_at field.
	chapter.DefaultCreatedAt = chapterDescCreatedAt.Default.(func() time.Time)
	// chapterDescUpdatedAt is the schema descriptor for updated_at field.
	chapterDescUpdatedAt := chapterFields[11].Descriptor()
	// chapter.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	chapter.DefaultUpdatedAt = chapterDescUpdatedAt.Default.(func() time.Time)
	// chapter.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	chapter.UpdateDefaultUpdatedAt = chapterDescUpdatedAt.UpdateDefault.(func() time.Time)
	chapterderivedtaskFields := schema.ChapterDerivedTask{}.Fields()
	_ = chapterderivedtaskFields
	// chapterderivedtaskDescChapterID is the schema descriptor for chapter_id field.
	chapterderivedtaskDescChapterID := chapterderivedtaskFields[0].Descriptor()
	// chapterderivedtask.ChapterIDValidator is a validator for the "chapter_id" field. It is called by the builders before save.
	chapterderivedtask.ChapterIDValidator = chapterderivedtaskDescChapterID.Validators[0].(func(int) error)
	// chapterderivedtaskDescAttempts is the schema descriptor for attempts field.
	chapterderivedtaskDescAttempts := chapterderivedtaskFields[4].Descriptor()
	// chapterderivedtask.DefaultAttempts holds the default value on creation for the attempts field.
	chapterderivedtask.DefaultAttempts = chapterderivedtaskDescAttempts.Default.(int)
	// chapterderivedtask.AttemptsValidator is a validator for the "attempts" field. It is called by the builders before save.
	chapterderivedtask.AttemptsValidator = chapterderivedtaskDescAttempts.Validators[0].(func(int) error)
	// chapterderivedtaskDescLeaseToken is the schema descriptor for lease_token field.
	chapterderivedtaskDescLeaseToken := chapterderivedtaskFields[5].Descriptor()
	// chapterderivedtask.DefaultLeaseToken holds the default value on creation for the lease_token field.
	chapterderivedtask.DefaultLeaseToken = chapterderivedtaskDescLeaseToken.Default.(string)
	// chapterderivedtaskDescLastError is the schema descriptor for last_error field.
	chapterderivedtaskDescLastError := chapterderivedtaskFields[7].Descriptor()
	// chapterderivedtask.DefaultLastError holds the default value on creation for the last_error field.
	chapterderivedtask.DefaultLastError = chapterderivedtaskDescLastError.Default.(string)
	// chapterderivedtaskDescCreatedAt is the schema descriptor for created_at field.
	chapterderivedtaskDescCreatedAt := chapterderivedtaskFields[8].Descriptor()
	// chapterderivedtask.DefaultCreatedAt holds the default value on creation for the created_at field.
	chapterderivedtask.DefaultCreatedAt = chapterderivedtaskDescCreatedAt.Default.(func() time.Time)
	// chapterderivedtaskDescUpdatedAt is the schema descriptor for updated_at field.
	chapterderivedtaskDescUpdatedAt := chapterderivedtaskFields[9].Descriptor()
	// chapterderivedtask.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	chapterderivedtask.DefaultUpdatedAt = chapterderivedtaskDescUpdatedAt.Default.(func() time.Time)
	// chapterderivedtask.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	chapterderivedtask.UpdateDefaultUpdatedAt = chapterderivedtaskDescUpdatedAt.UpdateDefault.(func() time.Time)
	characterFields := schema.Character{}.Fields()
	_ = characterFields
	// characterDescStateVersioned is the schema descriptor for state_versioned field.
	characterDescStateVersioned := characterFields[8].Descriptor()
	// character.DefaultStateVersioned holds the default value on creation for the state_versioned field.
	character.DefaultStateVersioned = characterDescStateVersioned.Default.(bool)
	// characterDescCreatedAt is the schema descriptor for created_at field.
	characterDescCreatedAt := characterFields[9].Descriptor()
	// character.DefaultCreatedAt holds the default value on creation for the created_at field.
	character.DefaultCreatedAt = characterDescCreatedAt.Default.(func() time.Time)
	// characterDescUpdatedAt is the schema descriptor for updated_at field.
	characterDescUpdatedAt := characterFields[10].Descriptor()
	// character.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	character.DefaultUpdatedAt = characterDescUpdatedAt.Default.(func() time.Time)
	// character.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	character.UpdateDefaultUpdatedAt = characterDescUpdatedAt.UpdateDefault.(func() time.Time)
	characterstateversionFields := schema.CharacterStateVersion{}.Fields()
	_ = characterstateversionFields
	// characterstateversionDescCharacterID is the schema descriptor for character_id field.
	characterstateversionDescCharacterID := characterstateversionFields[0].Descriptor()
	// characterstateversion.CharacterIDValidator is a validator for the "character_id" field. It is called by the builders before save.
	characterstateversion.CharacterIDValidator = characterstateversionDescCharacterID.Validators[0].(func(int) error)
	// characterstateversionDescChapterID is the schema descriptor for chapter_id field.
	characterstateversionDescChapterID := characterstateversionFields[1].Descriptor()
	// characterstateversion.ChapterIDValidator is a validator for the "chapter_id" field. It is called by the builders before save.
	characterstateversion.ChapterIDValidator = characterstateversionDescChapterID.Validators[0].(func(int) error)
	// characterstateversionDescChapterIndex is the schema descriptor for chapter_index field.
	characterstateversionDescChapterIndex := characterstateversionFields[2].Descriptor()
	// characterstateversion.ChapterIndexValidator is a validator for the "chapter_index" field. It is called by the builders before save.
	characterstateversion.ChapterIndexValidator = characterstateversionDescChapterIndex.Validators[0].(func(int) error)
	// characterstateversionDescValid is the schema descriptor for valid field.
	characterstateversionDescValid := characterstateversionFields[5].Descriptor()
	// characterstateversion.DefaultValid holds the default value on creation for the valid field.
	characterstateversion.DefaultValid = characterstateversionDescValid.Default.(bool)
	// characterstateversionDescCreatedAt is the schema descriptor for created_at field.
	characterstateversionDescCreatedAt := characterstateversionFields[6].Descriptor()
	// characterstateversion.DefaultCreatedAt holds the default value on creation for the created_at field.
	characterstateversion.DefaultCreatedAt = characterstateversionDescCreatedAt.Default.(func() time.Time)
	// characterstateversionDescUpdatedAt is the schema descriptor for updated_at field.
	characterstateversionDescUpdatedAt := characterstateversionFields[7].Descriptor()
	// characterstateversion.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	characterstateversion.DefaultUpdatedAt = characterstateversionDescUpdatedAt.Default.(func() time.Time)
	// characterstateversion.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	characterstateversion.UpdateDefaultUpdatedAt = characterstateversionDescUpdatedAt.UpdateDefault.(func() time.Time)
	memoryentryFields := schema.MemoryEntry{}.Fields()
	_ = memoryentryFields
	// memoryentryDescCreatedAt is the schema descriptor for created_at field.
	memoryentryDescCreatedAt := memoryentryFields[5].Descriptor()
	// memoryentry.DefaultCreatedAt holds the default value on creation for the created_at field.
	memoryentry.DefaultCreatedAt = memoryentryDescCreatedAt.Default.(func() time.Time)
	novelFields := schema.Novel{}.Fields()
	_ = novelFields
	// novelDescStatus is the schema descriptor for status field.
	novelDescStatus := novelFields[4].Descriptor()
	// novel.DefaultStatus holds the default value on creation for the status field.
	novel.DefaultStatus = novelDescStatus.Default.(string)
	// novelDescCreatedAt is the schema descriptor for created_at field.
	novelDescCreatedAt := novelFields[6].Descriptor()
	// novel.DefaultCreatedAt holds the default value on creation for the created_at field.
	novel.DefaultCreatedAt = novelDescCreatedAt.Default.(func() time.Time)
	// novelDescUpdatedAt is the schema descriptor for updated_at field.
	novelDescUpdatedAt := novelFields[7].Descriptor()
	// novel.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	novel.DefaultUpdatedAt = novelDescUpdatedAt.Default.(func() time.Time)
	// novel.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	novel.UpdateDefaultUpdatedAt = novelDescUpdatedAt.UpdateDefault.(func() time.Time)
	relationshipFields := schema.Relationship{}.Fields()
	_ = relationshipFields
	// relationshipDescStateVersioned is the schema descriptor for state_versioned field.
	relationshipDescStateVersioned := relationshipFields[3].Descriptor()
	// relationship.DefaultStateVersioned holds the default value on creation for the state_versioned field.
	relationship.DefaultStateVersioned = relationshipDescStateVersioned.Default.(bool)
	// relationshipDescCreatedAt is the schema descriptor for created_at field.
	relationshipDescCreatedAt := relationshipFields[4].Descriptor()
	// relationship.DefaultCreatedAt holds the default value on creation for the created_at field.
	relationship.DefaultCreatedAt = relationshipDescCreatedAt.Default.(func() time.Time)
	// relationshipDescUpdatedAt is the schema descriptor for updated_at field.
	relationshipDescUpdatedAt := relationshipFields[5].Descriptor()
	// relationship.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	relationship.DefaultUpdatedAt = relationshipDescUpdatedAt.Default.(func() time.Time)
	// relationship.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	relationship.UpdateDefaultUpdatedAt = relationshipDescUpdatedAt.UpdateDefault.(func() time.Time)
	relationshipstateversionFields := schema.RelationshipStateVersion{}.Fields()
	_ = relationshipstateversionFields
	// relationshipstateversionDescChapterID is the schema descriptor for chapter_id field.
	relationshipstateversionDescChapterID := relationshipstateversionFields[0].Descriptor()
	// relationshipstateversion.ChapterIDValidator is a validator for the "chapter_id" field. It is called by the builders before save.
	relationshipstateversion.ChapterIDValidator = relationshipstateversionDescChapterID.Validators[0].(func(int) error)
	// relationshipstateversionDescSourceCharacterID is the schema descriptor for source_character_id field.
	relationshipstateversionDescSourceCharacterID := relationshipstateversionFields[1].Descriptor()
	// relationshipstateversion.SourceCharacterIDValidator is a validator for the "source_character_id" field. It is called by the builders before save.
	relationshipstateversion.SourceCharacterIDValidator = relationshipstateversionDescSourceCharacterID.Validators[0].(func(int) error)
	// relationshipstateversionDescTargetCharacterID is the schema descriptor for target_character_id field.
	relationshipstateversionDescTargetCharacterID := relationshipstateversionFields[2].Descriptor()
	// relationshipstateversion.TargetCharacterIDValidator is a validator for the "target_character_id" field. It is called by the builders before save.
	relationshipstateversion.TargetCharacterIDValidator = relationshipstateversionDescTargetCharacterID.Validators[0].(func(int) error)
	// relationshipstateversionDescChapterIndex is the schema descriptor for chapter_index field.
	relationshipstateversionDescChapterIndex := relationshipstateversionFields[3].Descriptor()
	// relationshipstateversion.ChapterIndexValidator is a validator for the "chapter_index" field. It is called by the builders before save.
	relationshipstateversion.ChapterIndexValidator = relationshipstateversionDescChapterIndex.Validators[0].(func(int) error)
	// relationshipstateversionDescValid is the schema descriptor for valid field.
	relationshipstateversionDescValid := relationshipstateversionFields[8].Descriptor()
	// relationshipstateversion.DefaultValid holds the default value on creation for the valid field.
	relationshipstateversion.DefaultValid = relationshipstateversionDescValid.Default.(bool)
	// relationshipstateversionDescCreatedAt is the schema descriptor for created_at field.
	relationshipstateversionDescCreatedAt := relationshipstateversionFields[10].Descriptor()
	// relationshipstateversion.DefaultCreatedAt holds the default value on creation for the created_at field.
	relationshipstateversion.DefaultCreatedAt = relationshipstateversionDescCreatedAt.Default.(func() time.Time)
	// relationshipstateversionDescUpdatedAt is the schema descriptor for updated_at field.
	relationshipstateversionDescUpdatedAt := relationshipstateversionFields[11].Descriptor()
	// relationshipstateversion.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	relationshipstateversion.DefaultUpdatedAt = relationshipstateversionDescUpdatedAt.Default.(func() time.Time)
	// relationshipstateversion.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	relationshipstateversion.UpdateDefaultUpdatedAt = relationshipstateversionDescUpdatedAt.UpdateDefault.(func() time.Time)
	worldsettingFields := schema.WorldSetting{}.Fields()
	_ = worldsettingFields
	// worldsettingDescCurrentState is the schema descriptor for current_state field.
	worldsettingDescCurrentState := worldsettingFields[4].Descriptor()
	// worldsetting.DefaultCurrentState holds the default value on creation for the current_state field.
	worldsetting.DefaultCurrentState = worldsettingDescCurrentState.Default.(string)
	// worldsettingDescStateVersioned is the schema descriptor for state_versioned field.
	worldsettingDescStateVersioned := worldsettingFields[5].Descriptor()
	// worldsetting.DefaultStateVersioned holds the default value on creation for the state_versioned field.
	worldsetting.DefaultStateVersioned = worldsettingDescStateVersioned.Default.(bool)
	// worldsettingDescCreatedAt is the schema descriptor for created_at field.
	worldsettingDescCreatedAt := worldsettingFields[7].Descriptor()
	// worldsetting.DefaultCreatedAt holds the default value on creation for the created_at field.
	worldsetting.DefaultCreatedAt = worldsettingDescCreatedAt.Default.(func() time.Time)
	// worldsettingDescUpdatedAt is the schema descriptor for updated_at field.
	worldsettingDescUpdatedAt := worldsettingFields[8].Descriptor()
	// worldsetting.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	worldsetting.DefaultUpdatedAt = worldsettingDescUpdatedAt.Default.(func() time.Time)
	// worldsetting.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	worldsetting.UpdateDefaultUpdatedAt = worldsettingDescUpdatedAt.UpdateDefault.(func() time.Time)
	worldstateversionFields := schema.WorldStateVersion{}.Fields()
	_ = worldstateversionFields
	// worldstateversionDescWorldSettingID is the schema descriptor for world_setting_id field.
	worldstateversionDescWorldSettingID := worldstateversionFields[0].Descriptor()
	// worldstateversion.WorldSettingIDValidator is a validator for the "world_setting_id" field. It is called by the builders before save.
	worldstateversion.WorldSettingIDValidator = worldstateversionDescWorldSettingID.Validators[0].(func(int) error)
	// worldstateversionDescChapterID is the schema descriptor for chapter_id field.
	worldstateversionDescChapterID := worldstateversionFields[1].Descriptor()
	// worldstateversion.ChapterIDValidator is a validator for the "chapter_id" field. It is called by the builders before save.
	worldstateversion.ChapterIDValidator = worldstateversionDescChapterID.Validators[0].(func(int) error)
	// worldstateversionDescChapterIndex is the schema descriptor for chapter_index field.
	worldstateversionDescChapterIndex := worldstateversionFields[2].Descriptor()
	// worldstateversion.ChapterIndexValidator is a validator for the "chapter_index" field. It is called by the builders before save.
	worldstateversion.ChapterIndexValidator = worldstateversionDescChapterIndex.Validators[0].(func(int) error)
	// worldstateversionDescValid is the schema descriptor for valid field.
	worldstateversionDescValid := worldstateversionFields[5].Descriptor()
	// worldstateversion.DefaultValid holds the default value on creation for the valid field.
	worldstateversion.DefaultValid = worldstateversionDescValid.Default.(bool)
	// worldstateversionDescCreatedAt is the schema descriptor for created_at field.
	worldstateversionDescCreatedAt := worldstateversionFields[6].Descriptor()
	// worldstateversion.DefaultCreatedAt holds the default value on creation for the created_at field.
	worldstateversion.DefaultCreatedAt = worldstateversionDescCreatedAt.Default.(func() time.Time)
	// worldstateversionDescUpdatedAt is the schema descriptor for updated_at field.
	worldstateversionDescUpdatedAt := worldstateversionFields[7].Descriptor()
	// worldstateversion.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	worldstateversion.DefaultUpdatedAt = worldstateversionDescUpdatedAt.Default.(func() time.Time)
	// worldstateversion.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	worldstateversion.UpdateDefaultUpdatedAt = worldstateversionDescUpdatedAt.UpdateDefault.(func() time.Time)
}
