// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/ai-novel/studio/ent/chapter"
	"github.com/ai-novel/studio/ent/worldsetting"
	"github.com/ai-novel/studio/ent/worldstateversion"
)

// WorldStateVersion is the model entity for the WorldStateVersion schema.
type WorldStateVersion struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// WorldSettingID holds the value of the "world_setting_id" field.
	WorldSettingID int `json:"world_setting_id,omitempty"`
	// ChapterID holds the value of the "chapter_id" field.
	ChapterID int `json:"chapter_id,omitempty"`
	// ChapterIndex holds the value of the "chapter_index" field.
	ChapterIndex int `json:"chapter_index,omitempty"`
	// GenerationID holds the value of the "generation_id" field.
	GenerationID string `json:"generation_id,omitempty"`
	// CurrentState holds the value of the "current_state" field.
	CurrentState string `json:"current_state,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the WorldStateVersionQuery when eager-loading is set.
	Edges        WorldStateVersionEdges `json:"edges"`
	selectValues sql.SelectValues
}

// WorldStateVersionEdges holds the relations/edges for other nodes in the graph.
type WorldStateVersionEdges struct {
	// Chapter holds the value of the chapter edge.
	Chapter *Chapter `json:"chapter,omitempty"`
	// WorldSetting holds the value of the world_setting edge.
	WorldSetting *WorldSetting `json:"world_setting,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// ChapterOrErr returns the Chapter value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e WorldStateVersionEdges) ChapterOrErr() (*Chapter, error) {
	if e.Chapter != nil {
		return e.Chapter, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: chapter.Label}
	}
	return nil, &NotLoadedError{edge: "chapter"}
}

// WorldSettingOrErr returns the WorldSetting value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e WorldStateVersionEdges) WorldSettingOrErr() (*WorldSetting, error) {
	if e.WorldSetting != nil {
		return e.WorldSetting, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: worldsetting.Label}
	}
	return nil, &NotLoadedError{edge: "world_setting"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*WorldStateVersion) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case worldstateversion.FieldID, worldstateversion.FieldWorldSettingID, worldstateversion.FieldChapterID, worldstateversion.FieldChapterIndex:
			values[i] = new(sql.NullInt64)
		case worldstateversion.FieldGenerationID, worldstateversion.FieldCurrentState:
			values[i] = new(sql.NullString)
		case worldstateversion.FieldCreatedAt, worldstateversion.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the WorldStateVersion fields.
func (_m *WorldStateVersion) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case worldstateversion.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case worldstateversion.FieldWorldSettingID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field world_setting_id", values[i])
			} else if value.Valid {
				_m.WorldSettingID = int(value.Int64)
			}
		case worldstateversion.FieldChapterID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field chapter_id", values[i])
			} else if value.Valid {
				_m.ChapterID = int(value.Int64)
			}
		case worldstateversion.FieldChapterIndex:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field chapter_index", values[i])
			} else if value.Valid {
				_m.ChapterIndex = int(value.Int64)
			}
		case worldstateversion.FieldGenerationID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field generation_id", values[i])
			} else if value.Valid {
				_m.GenerationID = value.String
			}
		case worldstateversion.FieldCurrentState:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field current_state", values[i])
			} else if value.Valid {
				_m.CurrentState = value.String
			}
		case worldstateversion.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case worldstateversion.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the WorldStateVersion.
// This includes values selected through modifiers, order, etc.
func (_m *WorldStateVersion) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryChapter queries the "chapter" edge of the WorldStateVersion entity.
func (_m *WorldStateVersion) QueryChapter() *ChapterQuery {
	return NewWorldStateVersionClient(_m.config).QueryChapter(_m)
}

// QueryWorldSetting queries the "world_setting" edge of the WorldStateVersion entity.
func (_m *WorldStateVersion) QueryWorldSetting() *WorldSettingQuery {
	return NewWorldStateVersionClient(_m.config).QueryWorldSetting(_m)
}

// Update returns a builder for updating this WorldStateVersion.
// Note that you need to call WorldStateVersion.Unwrap() before calling this method if this WorldStateVersion
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *WorldStateVersion) Update() *WorldStateVersionUpdateOne {
	return NewWorldStateVersionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the WorldStateVersion entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *WorldStateVersion) Unwrap() *WorldStateVersion {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: WorldStateVersion is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *WorldStateVersion) String() string {
	var builder strings.Builder
	builder.WriteString("WorldStateVersion(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("world_setting_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.WorldSettingID))
	builder.WriteString(", ")
	builder.WriteString("chapter_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ChapterID))
	builder.WriteString(", ")
	builder.WriteString("chapter_index=")
	builder.WriteString(fmt.Sprintf("%v", _m.ChapterIndex))
	builder.WriteString(", ")
	builder.WriteString("generation_id=")
	builder.WriteString(_m.GenerationID)
	builder.WriteString(", ")
	builder.WriteString("current_state=")
	builder.WriteString(_m.CurrentState)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// WorldStateVersions is a parsable slice of WorldStateVersion.
type WorldStateVersions []*WorldStateVersion
