// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ai-novel/studio/ent/predicate"
	"github.com/ai-novel/studio/ent/worldsetting"
)

// WorldSettingUpdate is the builder for updating WorldSetting entities.
type WorldSettingUpdate struct {
	config
	hooks    []Hook
	mutation *WorldSettingMutation
}

// Where appends a list predicates to the WorldSettingUpdate builder.
func (_u *WorldSettingUpdate) Where(ps ...predicate.WorldSetting) *WorldSettingUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetNovelID sets the "novel_id" field.
func (_u *WorldSettingUpdate) SetNovelID(v string) *WorldSettingUpdate {
	_u.mutation.SetNovelID(v)
	return _u
}

// SetNillableNovelID sets the "novel_id" field if the given value is not nil.
func (_u *WorldSettingUpdate) SetNillableNovelID(v *string) *WorldSettingUpdate {
	if v != nil {
		_u.SetNovelID(*v)
	}
	return _u
}

// SetCategory sets the "category" field.
func (_u *WorldSettingUpdate) SetCategory(v string) *WorldSettingUpdate {
	_u.mutation.SetCategory(v)
	return _u
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_u *WorldSettingUpdate) SetNillableCategory(v *string) *WorldSettingUpdate {
	if v != nil {
		_u.SetCategory(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *WorldSettingUpdate) SetName(v string) *WorldSettingUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *WorldSettingUpdate) SetNillableName(v *string) *WorldSettingUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *WorldSettingUpdate) SetDescription(v string) *WorldSettingUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *WorldSettingUpdate) SetNillableDescription(v *string) *WorldSettingUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *WorldSettingUpdate) SetMetadata(v map[string]interface{}) *WorldSettingUpdate {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *WorldSettingUpdate) ClearMetadata() *WorldSettingUpdate {
	_u.mutation.ClearMetadata()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *WorldSettingUpdate) SetCreatedAt(v time.Time) *WorldSettingUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *WorldSettingUpdate) SetNillableCreatedAt(v *time.Time) *WorldSettingUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *WorldSettingUpdate) SetUpdatedAt(v time.Time) *WorldSettingUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the WorldSettingMutation object of the builder.
func (_u *WorldSettingUpdate) Mutation() *WorldSettingMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *WorldSettingUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WorldSettingUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *WorldSettingUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WorldSettingUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *WorldSettingUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := worldsetting.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *WorldSettingUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(worldsetting.Table, worldsetting.Columns, sqlgraph.NewFieldSpec(worldsetting.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.NovelID(); ok {
		_spec.SetField(worldsetting.FieldNovelID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Category(); ok {
		_spec.SetField(worldsetting.FieldCategory, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(worldsetting.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(worldsetting.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(worldsetting.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(worldsetting.FieldMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(worldsetting.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(worldsetting.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{worldsetting.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// WorldSettingUpdateOne is the builder for updating a single WorldSetting entity.
type WorldSettingUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *WorldSettingMutation
}

// SetNovelID sets the "novel_id" field.
func (_u *WorldSettingUpdateOne) SetNovelID(v string) *WorldSettingUpdateOne {
	_u.mutation.SetNovelID(v)
	return _u
}

// SetNillableNovelID sets the "novel_id" field if the given value is not nil.
func (_u *WorldSettingUpdateOne) SetNillableNovelID(v *string) *WorldSettingUpdateOne {
	if v != nil {
		_u.SetNovelID(*v)
	}
	return _u
}

// SetCategory sets the "category" field.
func (_u *WorldSettingUpdateOne) SetCategory(v string) *WorldSettingUpdateOne {
	_u.mutation.SetCategory(v)
	return _u
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_u *WorldSettingUpdateOne) SetNillableCategory(v *string) *WorldSettingUpdateOne {
	if v != nil {
		_u.SetCategory(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *WorldSettingUpdateOne) SetName(v string) *WorldSettingUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *WorldSettingUpdateOne) SetNillableName(v *string) *WorldSettingUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *WorldSettingUpdateOne) SetDescription(v string) *WorldSettingUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *WorldSettingUpdateOne) SetNillableDescription(v *string) *WorldSettingUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *WorldSettingUpdateOne) SetMetadata(v map[string]interface{}) *WorldSettingUpdateOne {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *WorldSettingUpdateOne) ClearMetadata() *WorldSettingUpdateOne {
	_u.mutation.ClearMetadata()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *WorldSettingUpdateOne) SetCreatedAt(v time.Time) *WorldSettingUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *WorldSettingUpdateOne) SetNillableCreatedAt(v *time.Time) *WorldSettingUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *WorldSettingUpdateOne) SetUpdatedAt(v time.Time) *WorldSettingUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the WorldSettingMutation object of the builder.
func (_u *WorldSettingUpdateOne) Mutation() *WorldSettingMutation {
	return _u.mutation
}

// Where appends a list predicates to the WorldSettingUpdate builder.
func (_u *WorldSettingUpdateOne) Where(ps ...predicate.WorldSetting) *WorldSettingUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *WorldSettingUpdateOne) Select(field string, fields ...string) *WorldSettingUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated WorldSetting entity.
func (_u *WorldSettingUpdateOne) Save(ctx context.Context) (*WorldSetting, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WorldSettingUpdateOne) SaveX(ctx context.Context) *WorldSetting {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *WorldSettingUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WorldSettingUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *WorldSettingUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := worldsetting.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *WorldSettingUpdateOne) sqlSave(ctx context.Context) (_node *WorldSetting, err error) {
	_spec := sqlgraph.NewUpdateSpec(worldsetting.Table, worldsetting.Columns, sqlgraph.NewFieldSpec(worldsetting.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "WorldSetting.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, worldsetting.FieldID)
		for _, f := range fields {
			if !worldsetting.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != worldsetting.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.NovelID(); ok {
		_spec.SetField(worldsetting.FieldNovelID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Category(); ok {
		_spec.SetField(worldsetting.FieldCategory, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(worldsetting.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(worldsetting.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(worldsetting.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(worldsetting.FieldMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(worldsetting.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(worldsetting.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &WorldSetting{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{worldsetting.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
