// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ai-novel/studio/ent/chapter"
	"github.com/ai-novel/studio/ent/predicate"
	"github.com/ai-novel/studio/ent/worldsetting"
	"github.com/ai-novel/studio/ent/worldstateversion"
)

// WorldStateVersionQuery is the builder for querying WorldStateVersion entities.
type WorldStateVersionQuery struct {
	config
	ctx              *QueryContext
	order            []worldstateversion.OrderOption
	inters           []Interceptor
	predicates       []predicate.WorldStateVersion
	withChapter      *ChapterQuery
	withWorldSetting *WorldSettingQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the WorldStateVersionQuery builder.
func (_q *WorldStateVersionQuery) Where(ps ...predicate.WorldStateVersion) *WorldStateVersionQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *WorldStateVersionQuery) Limit(limit int) *WorldStateVersionQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *WorldStateVersionQuery) Offset(offset int) *WorldStateVersionQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *WorldStateVersionQuery) Unique(unique bool) *WorldStateVersionQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *WorldStateVersionQuery) Order(o ...worldstateversion.OrderOption) *WorldStateVersionQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryChapter chains the current query on the "chapter" edge.
func (_q *WorldStateVersionQuery) QueryChapter() *ChapterQuery {
	query := (&ChapterClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(worldstateversion.Table, worldstateversion.FieldID, selector),
			sqlgraph.To(chapter.Table, chapter.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, worldstateversion.ChapterTable, worldstateversion.ChapterColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryWorldSetting chains the current query on the "world_setting" edge.
func (_q *WorldStateVersionQuery) QueryWorldSetting() *WorldSettingQuery {
	query := (&WorldSettingClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(worldstateversion.Table, worldstateversion.FieldID, selector),
			sqlgraph.To(worldsetting.Table, worldsetting.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, worldstateversion.WorldSettingTable, worldstateversion.WorldSettingColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first WorldStateVersion entity from the query.
// Returns a *NotFoundError when no WorldStateVersion was found.
func (_q *WorldStateVersionQuery) First(ctx context.Context) (*WorldStateVersion, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{worldstateversion.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *WorldStateVersionQuery) FirstX(ctx context.Context) *WorldStateVersion {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first WorldStateVersion ID from the query.
// Returns a *NotFoundError when no WorldStateVersion ID was found.
func (_q *WorldStateVersionQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{worldstateversion.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *WorldStateVersionQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single WorldStateVersion entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one WorldStateVersion entity is found.
// Returns a *NotFoundError when no WorldStateVersion entities are found.
func (_q *WorldStateVersionQuery) Only(ctx context.Context) (*WorldStateVersion, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{worldstateversion.Label}
	default:
		return nil, &NotSingularError{worldstateversion.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *WorldStateVersionQuery) OnlyX(ctx context.Context) *WorldStateVersion {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only WorldStateVersion ID in the query.
// Returns a *NotSingularError when more than one WorldStateVersion ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *WorldStateVersionQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{worldstateversion.Label}
	default:
		err = &NotSingularError{worldstateversion.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *WorldStateVersionQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of WorldStateVersions.
func (_q *WorldStateVersionQuery) All(ctx context.Context) ([]*WorldStateVersion, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*WorldStateVersion, *WorldStateVersionQuery]()
	return withInterceptors[[]*WorldStateVersion](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *WorldStateVersionQuery) AllX(ctx context.Context) []*WorldStateVersion {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of WorldStateVersion IDs.
func (_q *WorldStateVersionQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(worldstateversion.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *WorldStateVersionQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *WorldStateVersionQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*WorldStateVersionQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *WorldStateVersionQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *WorldStateVersionQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *WorldStateVersionQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the WorldStateVersionQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *WorldStateVersionQuery) Clone() *WorldStateVersionQuery {
	if _q == nil {
		return nil
	}
	return &WorldStateVersionQuery{
		config:           _q.config,
		ctx:              _q.ctx.Clone(),
		order:            append([]worldstateversion.OrderOption{}, _q.order...),
		inters:           append([]Interceptor{}, _q.inters...),
		predicates:       append([]predicate.WorldStateVersion{}, _q.predicates...),
		withChapter:      _q.withChapter.Clone(),
		withWorldSetting: _q.withWorldSetting.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithChapter tells the query-builder to eager-load the nodes that are connected to
// the "chapter" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *WorldStateVersionQuery) WithChapter(opts ...func(*ChapterQuery)) *WorldStateVersionQuery {
	query := (&ChapterClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withChapter = query
	return _q
}

// WithWorldSetting tells the query-builder to eager-load the nodes that are connected to
// the "world_setting" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *WorldStateVersionQuery) WithWorldSetting(opts ...func(*WorldSettingQuery)) *WorldStateVersionQuery {
	query := (&WorldSettingClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withWorldSetting = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		WorldSettingID int `json:"world_setting_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.WorldStateVersion.Query().
//		GroupBy(worldstateversion.FieldWorldSettingID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *WorldStateVersionQuery) GroupBy(field string, fields ...string) *WorldStateVersionGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &WorldStateVersionGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = worldstateversion.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		WorldSettingID int `json:"world_setting_id,omitempty"`
//	}
//
//	client.WorldStateVersion.Query().
//		Select(worldstateversion.FieldWorldSettingID).
//		Scan(ctx, &v)
func (_q *WorldStateVersionQuery) Select(fields ...string) *WorldStateVersionSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &WorldStateVersionSelect{WorldStateVersionQuery: _q}
	sbuild.label = worldstateversion.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a WorldStateVersionSelect configured with the given aggregations.
func (_q *WorldStateVersionQuery) Aggregate(fns ...AggregateFunc) *WorldStateVersionSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *WorldStateVersionQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !worldstateversion.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *WorldStateVersionQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*WorldStateVersion, error) {
	var (
		nodes       = []*WorldStateVersion{}
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withChapter != nil,
			_q.withWorldSetting != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*WorldStateVersion).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &WorldStateVersion{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withChapter; query != nil {
		if err := _q.loadChapter(ctx, query, nodes, nil,
			func(n *WorldStateVersion, e *Chapter) { n.Edges.Chapter = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withWorldSetting; query != nil {
		if err := _q.loadWorldSetting(ctx, query, nodes, nil,
			func(n *WorldStateVersion, e *WorldSetting) { n.Edges.WorldSetting = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *WorldStateVersionQuery) loadChapter(ctx context.Context, query *ChapterQuery, nodes []*WorldStateVersion, init func(*WorldStateVersion), assign func(*WorldStateVersion, *Chapter)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*WorldStateVersion)
	for i := range nodes {
		fk := nodes[i].ChapterID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(chapter.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "chapter_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *WorldStateVersionQuery) loadWorldSetting(ctx context.Context, query *WorldSettingQuery, nodes []*WorldStateVersion, init func(*WorldStateVersion), assign func(*WorldStateVersion, *WorldSetting)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*WorldStateVersion)
	for i := range nodes {
		fk := nodes[i].WorldSettingID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(worldsetting.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "world_setting_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *WorldStateVersionQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *WorldStateVersionQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(worldstateversion.Table, worldstateversion.Columns, sqlgraph.NewFieldSpec(worldstateversion.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, worldstateversion.FieldID)
		for i := range fields {
			if fields[i] != worldstateversion.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withChapter != nil {
			_spec.Node.AddColumnOnce(worldstateversion.FieldChapterID)
		}
		if _q.withWorldSetting != nil {
			_spec.Node.AddColumnOnce(worldstateversion.FieldWorldSettingID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *WorldStateVersionQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(worldstateversion.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = worldstateversion.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// WorldStateVersionGroupBy is the group-by builder for WorldStateVersion entities.
type WorldStateVersionGroupBy struct {
	selector
	build *WorldStateVersionQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *WorldStateVersionGroupBy) Aggregate(fns ...AggregateFunc) *WorldStateVersionGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *WorldStateVersionGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*WorldStateVersionQuery, *WorldStateVersionGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *WorldStateVersionGroupBy) sqlScan(ctx context.Context, root *WorldStateVersionQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// WorldStateVersionSelect is the builder for selecting fields of WorldStateVersion entities.
type WorldStateVersionSelect struct {
	*WorldStateVersionQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *WorldStateVersionSelect) Aggregate(fns ...AggregateFunc) *WorldStateVersionSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *WorldStateVersionSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*WorldStateVersionQuery, *WorldStateVersionSelect](ctx, _s.WorldStateVersionQuery, _s, _s.inters, v)
}

func (_s *WorldStateVersionSelect) sqlScan(ctx context.Context, root *WorldStateVersionQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
