// Code generated by ent, DO NOT EDIT.

package memoryentry

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the memoryentry type in the database.
	Label = "memory_entry"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldNovelID holds the string denoting the novel_id field in the database.
	FieldNovelID = "novel_id"
	// FieldContent holds the string denoting the content field in the database.
	FieldContent = "content"
	// FieldMetadata holds the string denoting the metadata field in the database.
	FieldMetadata = "metadata"
	// FieldEmbedding holds the string denoting the embedding field in the database.
	FieldEmbedding = "embedding"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the memoryentry in the database.
	Table = "memory_entries"
)

// Columns holds all SQL columns for memoryentry fields.
var Columns = []string{
	FieldID,
	FieldNovelID,
	FieldContent,
	FieldMetadata,
	FieldEmbedding,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the MemoryEntry queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByNovelID orders the results by the novel_id field.
func ByNovelID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNovelID, opts...).ToFunc()
}

// ByContent orders the results by the content field.
func ByContent(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContent, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}
