// Code generated by ent, DO NOT EDIT.

package memoryentry

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/ai-novel/studio/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldLTE(FieldID, id))
}

// NovelID applies equality check predicate on the "novel_id" field. It's identical to NovelIDEQ.
func NovelID(v string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldEQ(FieldNovelID, v))
}

// Content applies equality check predicate on the "content" field. It's identical to ContentEQ.
func Content(v string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldEQ(FieldContent, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldEQ(FieldCreatedAt, v))
}

// NovelIDEQ applies the EQ predicate on the "novel_id" field.
func NovelIDEQ(v string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldEQ(FieldNovelID, v))
}

// NovelIDNEQ applies the NEQ predicate on the "novel_id" field.
func NovelIDNEQ(v string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldNEQ(FieldNovelID, v))
}

// NovelIDIn applies the In predicate on the "novel_id" field.
func NovelIDIn(vs ...string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldIn(FieldNovelID, vs...))
}

// NovelIDNotIn applies the NotIn predicate on the "novel_id" field.
func NovelIDNotIn(vs ...string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldNotIn(FieldNovelID, vs...))
}

// NovelIDGT applies the GT predicate on the "novel_id" field.
func NovelIDGT(v string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldGT(FieldNovelID, v))
}

// NovelIDGTE applies the GTE predicate on the "novel_id" field.
func NovelIDGTE(v string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldGTE(FieldNovelID, v))
}

// NovelIDLT applies the LT predicate on the "novel_id" field.
func NovelIDLT(v string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldLT(FieldNovelID, v))
}

// NovelIDLTE applies the LTE predicate on the "novel_id" field.
func NovelIDLTE(v string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldLTE(FieldNovelID, v))
}

// NovelIDContains applies the Contains predicate on the "novel_id" field.
func NovelIDContains(v string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldContains(FieldNovelID, v))
}

// NovelIDHasPrefix applies the HasPrefix predicate on the "novel_id" field.
func NovelIDHasPrefix(v string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldHasPrefix(FieldNovelID, v))
}

// NovelIDHasSuffix applies the HasSuffix predicate on the "novel_id" field.
func NovelIDHasSuffix(v string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldHasSuffix(FieldNovelID, v))
}

// NovelIDEqualFold applies the EqualFold predicate on the "novel_id" field.
func NovelIDEqualFold(v string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldEqualFold(FieldNovelID, v))
}

// NovelIDContainsFold applies the ContainsFold predicate on the "novel_id" field.
func NovelIDContainsFold(v string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldContainsFold(FieldNovelID, v))
}

// ContentEQ applies the EQ predicate on the "content" field.
func ContentEQ(v string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldEQ(FieldContent, v))
}

// ContentNEQ applies the NEQ predicate on the "content" field.
func ContentNEQ(v string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldNEQ(FieldContent, v))
}

// ContentIn applies the In predicate on the "content" field.
func ContentIn(vs ...string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldIn(FieldContent, vs...))
}

// ContentNotIn applies the NotIn predicate on the "content" field.
func ContentNotIn(vs ...string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldNotIn(FieldContent, vs...))
}

// ContentGT applies the GT predicate on the "content" field.
func ContentGT(v string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldGT(FieldContent, v))
}

// ContentGTE applies the GTE predicate on the "content" field.
func ContentGTE(v string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldGTE(FieldContent, v))
}

// ContentLT applies the LT predicate on the "content" field.
func ContentLT(v string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldLT(FieldContent, v))
}

// ContentLTE applies the LTE predicate on the "content" field.
func ContentLTE(v string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldLTE(FieldContent, v))
}

// ContentContains applies the Contains predicate on the "content" field.
func ContentContains(v string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldContains(FieldContent, v))
}

// ContentHasPrefix applies the HasPrefix predicate on the "content" field.
func ContentHasPrefix(v string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldHasPrefix(FieldContent, v))
}

// ContentHasSuffix applies the HasSuffix predicate on the "content" field.
func ContentHasSuffix(v string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldHasSuffix(FieldContent, v))
}

// ContentEqualFold applies the EqualFold predicate on the "content" field.
func ContentEqualFold(v string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldEqualFold(FieldContent, v))
}

// ContentContainsFold applies the ContainsFold predicate on the "content" field.
func ContentContainsFold(v string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldContainsFold(FieldContent, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.MemoryEntry) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.MemoryEntry) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.MemoryEntry) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.NotPredicates(p))
}
