// Code generated by ent, DO NOT EDIT.

package relationship

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the relationship type in the database.
	Label = "relationship"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldNovelID holds the string denoting the novel_id field in the database.
	FieldNovelID = "novel_id"
	// FieldRelationType holds the string denoting the relation_type field in the database.
	FieldRelationType = "relation_type"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeCharacter holds the string denoting the character edge name in mutations.
	EdgeCharacter = "character"
	// EdgeTargetCharacter holds the string denoting the target_character edge name in mutations.
	EdgeTargetCharacter = "target_character"
	// Table holds the table name of the relationship in the database.
	Table = "relationships"
	// CharacterTable is the table that holds the character relation/edge.
	CharacterTable = "relationships"
	// CharacterInverseTable is the table name for the Character entity.
	// It exists in this package in order to avoid circular dependency with the "character" package.
	CharacterInverseTable = "characters"
	// CharacterColumn is the table column denoting the character relation/edge.
	CharacterColumn = "character_relationships"
	// TargetCharacterTable is the table that holds the target_character relation/edge.
	TargetCharacterTable = "relationships"
	// TargetCharacterInverseTable is the table name for the Character entity.
	// It exists in this package in order to avoid circular dependency with the "character" package.
	TargetCharacterInverseTable = "characters"
	// TargetCharacterColumn is the table column denoting the target_character relation/edge.
	TargetCharacterColumn = "relationship_target_character"
)

// Columns holds all SQL columns for relationship fields.
var Columns = []string{
	FieldID,
	FieldNovelID,
	FieldRelationType,
	FieldDescription,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "relationships"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"character_relationships",
	"relationship_target_character",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the Relationship queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByNovelID orders the results by the novel_id field.
func ByNovelID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNovelID, opts...).ToFunc()
}

// ByRelationType orders the results by the relation_type field.
func ByRelationType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRelationType, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByCharacterField orders the results by character field.
func ByCharacterField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCharacterStep(), sql.OrderByField(field, opts...))
	}
}

// ByTargetCharacterField orders the results by target_character field.
func ByTargetCharacterField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTargetCharacterStep(), sql.OrderByField(field, opts...))
	}
}
func newCharacterStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CharacterInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, CharacterTable, CharacterColumn),
	)
}
func newTargetCharacterStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TargetCharacterInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, TargetCharacterTable, TargetCharacterColumn),
	)
}
