// Code generated by ent, DO NOT EDIT.

package relationship

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/ai-novel/studio/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Relationship {
	return predicate.Relationship(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Relationship {
	return predicate.Relationship(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Relationship {
	return predicate.Relationship(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Relationship {
	return predicate.Relationship(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Relationship {
	return predicate.Relationship(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Relationship {
	return predicate.Relationship(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Relationship {
	return predicate.Relationship(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Relationship {
	return predicate.Relationship(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Relationship {
	return predicate.Relationship(sql.FieldLTE(FieldID, id))
}

// NovelID applies equality check predicate on the "novel_id" field. It's identical to NovelIDEQ.
func NovelID(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldEQ(FieldNovelID, v))
}

// RelationType applies equality check predicate on the "relation_type" field. It's identical to RelationTypeEQ.
func RelationType(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldEQ(FieldRelationType, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldEQ(FieldDescription, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Relationship {
	return predicate.Relationship(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Relationship {
	return predicate.Relationship(sql.FieldEQ(FieldUpdatedAt, v))
}

// NovelIDEQ applies the EQ predicate on the "novel_id" field.
func NovelIDEQ(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldEQ(FieldNovelID, v))
}

// NovelIDNEQ applies the NEQ predicate on the "novel_id" field.
func NovelIDNEQ(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldNEQ(FieldNovelID, v))
}

// NovelIDIn applies the In predicate on the "novel_id" field.
func NovelIDIn(vs ...string) predicate.Relationship {
	return predicate.Relationship(sql.FieldIn(FieldNovelID, vs...))
}

// NovelIDNotIn applies the NotIn predicate on the "novel_id" field.
func NovelIDNotIn(vs ...string) predicate.Relationship {
	return predicate.Relationship(sql.FieldNotIn(FieldNovelID, vs...))
}

// NovelIDGT applies the GT predicate on the "novel_id" field.
func NovelIDGT(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldGT(FieldNovelID, v))
}

// NovelIDGTE applies the GTE predicate on the "novel_id" field.
func NovelIDGTE(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldGTE(FieldNovelID, v))
}

// NovelIDLT applies the LT predicate on the "novel_id" field.
func NovelIDLT(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldLT(FieldNovelID, v))
}

// NovelIDLTE applies the LTE predicate on the "novel_id" field.
func NovelIDLTE(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldLTE(FieldNovelID, v))
}

// NovelIDContains applies the Contains predicate on the "novel_id" field.
func NovelIDContains(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldContains(FieldNovelID, v))
}

// NovelIDHasPrefix applies the HasPrefix predicate on the "novel_id" field.
func NovelIDHasPrefix(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldHasPrefix(FieldNovelID, v))
}

// NovelIDHasSuffix applies the HasSuffix predicate on the "novel_id" field.
func NovelIDHasSuffix(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldHasSuffix(FieldNovelID, v))
}

// NovelIDEqualFold applies the EqualFold predicate on the "novel_id" field.
func NovelIDEqualFold(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldEqualFold(FieldNovelID, v))
}

// NovelIDContainsFold applies the ContainsFold predicate on the "novel_id" field.
func NovelIDContainsFold(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldContainsFold(FieldNovelID, v))
}

// RelationTypeEQ applies the EQ predicate on the "relation_type" field.
func RelationTypeEQ(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldEQ(FieldRelationType, v))
}

// RelationTypeNEQ applies the NEQ predicate on the "relation_type" field.
func RelationTypeNEQ(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldNEQ(FieldRelationType, v))
}

// RelationTypeIn applies the In predicate on the "relation_type" field.
func RelationTypeIn(vs ...string) predicate.Relationship {
	return predicate.Relationship(sql.FieldIn(FieldRelationType, vs...))
}

// RelationTypeNotIn applies the NotIn predicate on the "relation_type" field.
func RelationTypeNotIn(vs ...string) predicate.Relationship {
	return predicate.Relationship(sql.FieldNotIn(FieldRelationType, vs...))
}

// RelationTypeGT applies the GT predicate on the "relation_type" field.
func RelationTypeGT(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldGT(FieldRelationType, v))
}

// RelationTypeGTE applies the GTE predicate on the "relation_type" field.
func RelationTypeGTE(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldGTE(FieldRelationType, v))
}

// RelationTypeLT applies the LT predicate on the "relation_type" field.
func RelationTypeLT(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldLT(FieldRelationType, v))
}

// RelationTypeLTE applies the LTE predicate on the "relation_type" field.
func RelationTypeLTE(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldLTE(FieldRelationType, v))
}

// RelationTypeContains applies the Contains predicate on the "relation_type" field.
func RelationTypeContains(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldContains(FieldRelationType, v))
}

// RelationTypeHasPrefix applies the HasPrefix predicate on the "relation_type" field.
func RelationTypeHasPrefix(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldHasPrefix(FieldRelationType, v))
}

// RelationTypeHasSuffix applies the HasSuffix predicate on the "relation_type" field.
func RelationTypeHasSuffix(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldHasSuffix(FieldRelationType, v))
}

// RelationTypeEqualFold applies the EqualFold predicate on the "relation_type" field.
func RelationTypeEqualFold(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldEqualFold(FieldRelationType, v))
}

// RelationTypeContainsFold applies the ContainsFold predicate on the "relation_type" field.
func RelationTypeContainsFold(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldContainsFold(FieldRelationType, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.Relationship {
	return predicate.Relationship(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.Relationship {
	return predicate.Relationship(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.Relationship {
	return predicate.Relationship(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.Relationship {
	return predicate.Relationship(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldContainsFold(FieldDescription, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Relationship {
	return predicate.Relationship(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Relationship {
	return predicate.Relationship(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Relationship {
	return predicate.Relationship(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Relationship {
	return predicate.Relationship(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Relationship {
	return predicate.Relationship(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Relationship {
	return predicate.Relationship(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Relationship {
	return predicate.Relationship(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Relationship {
	return predicate.Relationship(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Relationship {
	return predicate.Relationship(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Relationship {
	return predicate.Relationship(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Relationship {
	return predicate.Relationship(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Relationship {
	return predicate.Relationship(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Relationship {
	return predicate.Relationship(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Relationship {
	return predicate.Relationship(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Relationship {
	return predicate.Relationship(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Relationship {
	return predicate.Relationship(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasCharacter applies the HasEdge predicate on the "character" edge.
func HasCharacter() predicate.Relationship {
	return predicate.Relationship(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, CharacterTable, CharacterColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCharacterWith applies the HasEdge predicate on the "character" edge with a given conditions (other predicates).
func HasCharacterWith(preds ...predicate.Character) predicate.Relationship {
	return predicate.Relationship(func(s *sql.Selector) {
		step := newCharacterStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasTargetCharacter applies the HasEdge predicate on the "target_character" edge.
func HasTargetCharacter() predicate.Relationship {
	return predicate.Relationship(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, TargetCharacterTable, TargetCharacterColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTargetCharacterWith applies the HasEdge predicate on the "target_character" edge with a given conditions (other predicates).
func HasTargetCharacterWith(preds ...predicate.Character) predicate.Relationship {
	return predicate.Relationship(func(s *sql.Selector) {
		step := newTargetCharacterStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Relationship) predicate.Relationship {
	return predicate.Relationship(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Relationship) predicate.Relationship {
	return predicate.Relationship(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Relationship) predicate.Relationship {
	return predicate.Relationship(sql.NotPredicates(p))
}
